# {.experimental: "codeReordering".}

type Dummy = object
import types, tables

proc add*(parent: var CsNamespace; item: CsEnum) =

  parent.enums.add item
  parent.enumTable[item.name] = item

proc add*(parent: var CsEnum; item: CsEnumMember) =
  parent.items.add item

proc add*(parent: var CsClass; m: CsMethod) =
  parent.methods.add m


proc add*(parent: var Dummy; item: CsAliasQualifiedName) = discard # TODO
proc add*(parent: var Dummy; item: CsAnonymousMethodExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsAnonymousObjectCreationExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsAnonymousObjectMemberDeclarator) = discard # TODO
proc add*(parent: var Dummy; item: CsArgument) = discard # TODO
proc add*(parent: var Dummy; item: CsArrayCreationExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsArrayRankSpecifier) = discard # TODO
proc add*(parent: var Dummy; item: CsArrayType) = discard # TODO
proc add*(parent: var Dummy; item: CsArrowExpressionClause) = discard # TODO
proc add*(parent: var Dummy; item: CsAssignmentExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsAttribute) = discard # TODO
proc add*(parent: var Dummy; item: CsAttributeArgument) = discard # TODO
proc add*(parent: var Dummy; item: CsAttributeArgumentList) = discard # TODO
proc add*(parent: var Dummy; item: CsAttributeList) = discard # TODO
proc add*(parent: var Dummy; item: CsAttributeTargetSpecifier) = discard # TODO
proc add*(parent: var Dummy; item: CsAwaitExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsBaseExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsBaseList) = discard # TODO
proc add*(parent: var Dummy; item: CsBinaryExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsBracketedArgumentList) = discard # TODO
proc add*(parent: var Dummy; item: CsBracketedParameterList) = discard # TODO
proc add*(parent: var Dummy; item: CsBreakStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsCasePatternSwitchLabel) = discard # TODO
proc add*(parent: var Dummy; item: CsCaseSwitchLabel) = discard # TODO
proc add*(parent: var Dummy; item: CsCastExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsCatch) = discard # TODO
proc add*(parent: var Dummy; item: CsCatchClause) = discard # TODO
proc add*(parent: var Dummy; item: CsCatchFilterClause) = discard # TODO
proc add*(parent: var Dummy; item: CsCheckedExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsCheckedStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsClassOrStructConstraint) = discard # TODO
proc add*(parent: var Dummy; item: CsConditionalAccessExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsConditionalExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsConstantPattern) = discard # TODO
proc add*(parent: var Dummy; item: CsConstructor) = discard # TODO
proc add*(parent: var Dummy; item: CsConstructorConstraint) = discard # TODO
proc add*(parent: var Dummy; item: CsConstructorInitializer) = discard # TODO
proc add*(parent: var Dummy; item: CsContinueStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsConversionOperator) = discard # TODO
proc add*(parent: var Dummy; item: CsDeclarationExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsDeclarationPattern) = discard # TODO
proc add*(parent: var Dummy; item: CsDefaultExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsDefaultSwitchLabel) = discard # TODO
proc add*(parent: var Dummy; item: CsDelegate) = discard # TODO
proc add*(parent: var Dummy; item: CsDestructor) = discard # TODO
proc add*(parent: var Dummy; item: CsDiscardDesignation) = discard # TODO
proc add*(parent: var Dummy; item: CsDoStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsElementAccessExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsElementBindingExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsElseClause) = discard # TODO
proc add*(parent: var Dummy; item: CsEmptyStatement) = discard # TODO

proc add*(parent: var Dummy; item: CsEqualsValueClause) = discard # TODO
proc add*(parent: var Dummy; item: CsEvent) = discard # TODO
proc add*(parent: var Dummy; item: CsEventField) = discard # TODO
proc add*(parent: var Dummy; item: CsExplicitInterfaceSpecifier) = discard # TODO
proc add*(parent: var Dummy; item: CsExpressionStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsExternAliasDirective) = discard # TODO
proc add*(parent: var Dummy; item: CsField) = discard # TODO
proc add*(parent: var Dummy; item: CsFinallyClause) = discard # TODO
proc add*(parent: var Dummy; item: CsFixedStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsForEachStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsForEachVariableStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsForStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsFromClause) = discard # TODO
proc add*(parent: var Dummy; item: CsGenericName) = discard # TODO
proc add*(parent: var Dummy; item: CsGlobalStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsGotoStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsGroupClause) = discard # TODO
proc add*(parent: var Dummy; item: CsIfStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsImplicitArrayCreationExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsImplicitElementAccess) = discard # TODO
proc add*(parent: var Dummy; item: CsIncompleteMember) = discard # TODO
proc add*(parent: var Dummy; item: CsIndexer) = discard # TODO
proc add*(parent: var Dummy; item: CsInitializerExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsInterface) = discard # TODO
proc add*(parent: var Dummy; item: CsInterpolatedStringExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsInterpolatedStringText) = discard # TODO
proc add*(parent: var Dummy; item: CsInterpolation) = discard # TODO
proc add*(parent: var Dummy; item: CsInterpolationAlignmentClause) = discard # TODO
proc add*(parent: var Dummy; item: CsInterpolationFormatClause) = discard # TODO
proc add*(parent: var Dummy; item: CsIsPatternExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsJoinClause) = discard # TODO
proc add*(parent: var Dummy; item: CsJoinIntoClause) = discard # TODO
proc add*(parent: var Dummy; item: CsLabeledStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsLetClause) = discard # TODO
proc add*(parent: var Dummy; item: CsLocalDeclarationStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsLocalFunctionStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsLockStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsMakeRefExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsMemberBindingExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsNameColon) = discard # TODO
proc add*(parent: var Dummy; item: CsNameEquals) = discard # TODO
proc add*(parent: var Dummy; item: CsNullableType) = discard # TODO
proc add*(parent: var Dummy; item: CsObjectCreationExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsOmittedArraySizeExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsOmittedTypeArgument) = discard # TODO
proc add*(parent: var Dummy; item: CsOperator) = discard # TODO
proc add*(parent: var Dummy; item: CsOrderByClause) = discard # TODO
proc add*(parent: var Dummy; item: CsOrdering) = discard # TODO
proc add*(parent: var Dummy; item: CsParameter) = discard # TODO
proc add*(parent: var Dummy; item: CsParameterList) = discard # TODO
proc add*(parent: var Dummy; item: CsParenthesizedExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsParenthesizedLambdaExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsParenthesizedVariableDesignation) = discard # TODO
proc add*(parent: var Dummy; item: CsPointerType) = discard # TODO
proc add*(parent: var Dummy; item: CsPostfixUnaryExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsPrefixUnaryExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsProperty) = discard # TODO
proc add*(parent: var Dummy; item: CsQueryBody) = discard # TODO
proc add*(parent: var Dummy; item: CsQueryContinuation) = discard # TODO
proc add*(parent: var Dummy; item: CsQueryExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsRefExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsRefType) = discard # TODO
proc add*(parent: var Dummy; item: CsRefValueExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsReturnStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsSelectClause) = discard # TODO
proc add*(parent: var Dummy; item: CsSimpleBaseType) = discard # TODO
proc add*(parent: var Dummy; item: CsSimpleLambdaExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsSingleVariableDesignation) = discard # TODO
proc add*(parent: var Dummy; item: CsSizeOfExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsStackAllocArrayCreationExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsStruct) = discard # TODO
proc add*(parent: var Dummy; item: CsSwitchSection) = discard # TODO
proc add*(parent: var Dummy; item: CsSwitchStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsThisExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsThrowExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsThrowStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsTryStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsTupleElement) = discard # TODO
proc add*(parent: var Dummy; item: CsTupleExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsTupleType) = discard # TODO
proc add*(parent: var Dummy; item: CsTypeArgumentList) = discard # TODO
proc add*(parent: var Dummy; item: CsTypeOfExpression) = discard # TODO
proc add*(parent: var Dummy; item: CsTypeParameter) = discard # TODO
proc add*(parent: var Dummy; item: CsTypeParameterConstraintClause) = discard # TODO
proc add*(parent: var Dummy; item: CsTypeParameterList) = discard # TODO
proc add*(parent: var Dummy; item: CsUnsafeStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsUsingStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsWhenClause) = discard # TODO
proc add*(parent: var Dummy; item: CsWhereClause) = discard # TODO
proc add*(parent: var Dummy; item: CsWhileStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsYieldStatement) = discard # TODO
proc add*(parent: var Dummy; item: CsRefTypeExpression) = discard # TODO
