import construct, constructs/justtypes
proc cfits*(parent, item: Construct; data: AllNeededData): bool = # asks the inner types to implement fits for these type arguments.
  result = case $parent.kind & ", " & $item.kind
  of "ckNamespace, ckClass": true
  of "ckParenthesizedExpression, ckAwaitExpression": true
  of "ckMemberAccessExpression, ckAliasQualifiedName": true
  of "ckClass, ckField": true
  of "ckNamespace, ckDelegate": true
  of "ckParenthesizedExpression, ckSimpleLambdaExpression": true
  of "ckNamespace, ckEnum": true
  of "ckEnum, ckEnumMember": true
  of "ckClass, ckMethod": true
  of "ckMethod, ckParameterList": true
  of "ckMethod, ckPredefinedType": true
  of "ckMethod, ckLocalDeclarationStatement": true
  of "ckMethod, ckReturnStatement": true
  of "ckEnumMember, ckEqualsValueClause": true
  of "ckEnumMember, ckLiteralExpression": true
  of "ckReturnStatement, ckLiteralExpression": true
  of "ckParameterList, ckParameter": true
  of "ckClass, ckBaseList": true
  of "ckClass, ckSimpleBaseType": true
  of "ckConstructor, ckParameterList": true
  of "ckClass, ckConstructor": true
  of "ckClass, ckIndexer": true
  of "ckIndexer, ckPredefinedType": true
  of "ckIndexer, ckExplicitInterfaceSpecifier": true
  of "ckIndexer, ckBracketedParameterList": true
  of "ckIndexer, ckParameter": true
  of "ckIndexer, ckAccessorList": true
  of "ckAccessorList, ckAccessor": true
  of "ckClass, ckProperty": true
  of "ckProperty, ckPredefinedType": true
  of "ckProperty, ckAccessorList": true
  of "ckNamespace, ckUsingDirective": true
  of "ckMethod, ckExpressionStatement": true
  of "ckMethod, ckInvocationExpression": true
  of "ckExpressionStatement, ckInvocationExpression": true
  of "ckExpressionStatement, ckArgumentList": true
  of "ckExpressionStatement, ckArgument": true
  of "ckConstructor, ckExpressionStatement": true
  of "ckConstructor, ckAssignmentExpression": true
  of "ckConstructor, ckConstructorInitializer": true
  of "ckConstructor, ckArgumentList": true # likely for initializer
  of "ckLocalDeclarationStatement, ckVariable": true
  of "ckLocalDeclarationStatement, ckGenericName": true
  of "ckLocalDeclarationStatement, ckTypeArgumentList": true
  of "ckLocalDeclarationStatement, ckVariableDeclarator": true
  of "ckVariableDeclarator, ckEqualsValueClause": true
  of "ckVariableDeclarator, ckObjectCreationExpression": true
  of "ckLocalDeclarationStatement, ckArgumentList": true
  of "ckMethod, ckAssignmentExpression": true
  of "ckAssignmentExpression, ckObjectCreationExpression": true
  of "ckReturnStatement, ckObjectCreationExpression": true
  of "ckReturnStatement, ckArgumentList": true
  of "ckLocalDeclarationStatement, ckLiteralExpression": true
  of "ckAssignmentExpression, ckGenericName": true
  of "ckAssignmentExpression, ckTypeArgumentList": true
  of "ckAssignmentExpression, ckArgumentList": true
  of "ckObjectCreationExpression, ckInitializerExpression": true
  of "ckInitializerExpression, ckLiteralExpression": true
  of "ckLiteralExpression, ckPrefixUnaryExpression": true
  of "ckInitializerExpression, ckPrefixUnaryExpression": true
  of "ckVariableDeclarator, ckBinaryExpression": true
  of "ckVariable, ckGenericName": true
  of "ckObjectCreationExpression, ckGenericName": true
  of "ckGenericName, ckTypeArgumentList": true
  of "ckUsingDirective, ckNameEquals": true
  of "ckNameEquals, ckGenericName": true
  of "ckParameter, ckGenericName": true
  of "ckField, ckVariable": true
  of "ckReturnStatement, ckMemberAccessExpression": true
  of "ckField, ckVariableDeclarator": true
  of "ckMethod, ckVariableDeclarator": true
  of "ckVariableDeclarator, ckMemberAccessExpression": true
  of "ckInvocationExpression, ckMemberAccessExpression": true
  of "ckVariable, ckPredefinedType": true
  of "ckVariable, ckVariableDeclarator": true
  of "ckEqualsValueClause, ckLiteralExpression": true
  of "ckInvocationExpression, ckArgumentList": true
  of "ckConditionalExpression, ckPrefixUnaryExpression": true
  of "ckSimpleLambdaExpression, ckConditionalExpression": true
  of "ckInitializerExpression, ckConditionalExpression": true
  of "ckConditionalExpression, ckThisExpression": true
  of "ckArrayRankSpecifier, ckMemberAccessExpression": true
  of "ckInitializerExpression, ckTypeOfExpression": true
  of "ckEqualsValueClause, ckParenthesizedExpression": true
  of "ckCastExpression, ckConditionalAccessExpression": true
  of "ckNamespace, ckStruct": true
  of "ckSimpleLambdaExpression, ckQueryExpression": true
  of "ckArgument, ckDeclarationExpression": true
  of "ckTypeArgumentList, ckTupleType": true
  of "ckEqualsValueClause, ckAnonymousObjectCreationExpression": true
  of "ckBinaryExpression, ckIsPatternExpression": true
  of "ckArgument, ckAwaitExpression": true
  of "ckIfStatement, ckIsPatternExpression": true
  of "ckClass, ckStruct": true
  of "ckMethod, ckLockStatement": true
  of "ckAssignmentExpression, ckImplicitArrayCreationExpression": true
  of "ckForStatement, ckEmptyStatement": true
  of "ckAssignmentExpression, ckImplicitElementAccess": true
  of "ckConditionalExpression, ckAwaitExpression": true
  of "ckEqualsValueClause, ckQueryExpression": true
  of "ckVariable, ckRefType": true
  of "ckMethod, ckTupleType": true
  of "ckVariable, ckPointerType": true
  of "ckExpressionStatement, ckConditionalAccessExpression": true
  of "ckIfStatement, ckYieldStatement": true
  of "ckParenthesizedExpression, ckQueryExpression": true
  of "ckIfStatement, ckContinueStatement": true
  of "ckUsingDirective, ckAliasQualifiedName": true
  of "ckAssignmentExpression, ckDeclarationExpression": true
  of "ckBinaryExpression, ckThrowExpression": true
  of "ckCastExpression, ckElementAccessExpression": true
  of "ckCastExpression, ckObjectCreationExpression": true
  of "ckConstructor, ckReturnStatement": true
  of "ckCastExpression, ckCastExpression": true
  of "ckConditionalExpression, ckObjectCreationExpression": true
  of "ckArgumentList, ckArgument": true
  of "ckPostfixUnaryExpression, ckElementAccessExpression": true
  of "ckIfStatement, ckElementAccessExpression": true
  of "ckElementAccessExpression, ckParenthesizedExpression": true
  of "ckPostfixUnaryExpression, ckInvocationExpression": true
  of "ckParenthesizedLambdaExpression, ckTypeOfExpression": true
  of "ckInitializerExpression, ckSimpleLambdaExpression": true
  of "ckArgument, ckLiteralExpression": true
  of "ckTypeArgumentList, ckPredefinedType": true
  of "ckEqualsValueClause, ckObjectCreationExpression": true
  of "ckObjectCreationExpression, ckArgumentList": true
  of "ckPrefixUnaryExpression, ckLiteralExpression": true
  of "ckParameter, ckPredefinedType": true
  of "ckBracketedParameterList, ckParameter": true
  of "ckEqualsValueClause, ckMemberAccessExpression": true
  of "ckEqualsValueClause, ckBinaryExpression": true
  of "ckBaseList, ckSimpleBaseType": true
  of "ckArgument, ckAssignmentExpression": true
  of "ckArgument, ckBinaryExpression": true
  of "ckArgument, ckInvocationExpression": true
  of "ckArgument, ckMemberAccessExpression": true
  of "ckArgument, ckObjectCreationExpression": true
  of "ckArgument, ckPrefixUnaryExpression": true
  of "ckClass, ckClass": true
  of "ckClass, ckEnum": true
  of "ckConstructor, ckLocalDeclarationStatement": true
  of "ckConstructorInitializer, ckArgumentList": true
  of "ckEqualsValueClause, ckInvocationExpression": true
  of "ckExpressionStatement, ckAssignmentExpression": true
  of "ckInitializerExpression, ckAssignmentExpression": true
  of "ckInitializerExpression, ckInitializerExpression": true
  of "ckInitializerExpression, ckMemberAccessExpression": true
  of "ckInitializerExpression, ckObjectCreationExpression": true
  of "ckMemberAccessExpression, ckGenericName": true
  of "ckMemberAccessExpression, ckInvocationExpression": true
  of "ckMemberAccessExpression, ckMemberAccessExpression": true
  of "ckMemberAccessExpression, ckObjectCreationExpression": true
  of "ckMethod, ckGenericName": true
  of "ckObjectCreationExpression, ckPredefinedType": true
  of "ckParameter, ckEqualsValueClause": true
  of "ckReturnStatement, ckInvocationExpression": true
  of "ckTypeArgumentList, ckGenericName": true
  of "ckUsingDirective, ckGenericName": true
  of "ckLockStatement, ckThisExpression": true
  of "ckNullableType, ckGenericName": true
  of "ckConditionalAccessExpression, ckInvocationExpression": true
  of "ckYieldStatement, ckArrayCreationExpression": true
  of "ckIsPatternExpression, ckConditionalAccessExpression": true
  of "ckImplicitArrayCreationExpression, ckInitializerExpression": true
  of "ckNullableType, ckArrayType": true
  of "ckAwaitExpression, ckInvocationExpression": true
  of "ckPointerType, ckPredefinedType": true
  of "ckForEachStatement, ckInvocationExpression": true
  of "ckInterface, ckMethod": true
  of "ckElseClause, ckIfStatement": true
  of "ckNullableType, ckPredefinedType": true
  of "ckForEachStatement, ckExpressionStatement": true
  of "ckForEachStatement, ckMemberAccessExpression": true
  of "ckStruct, ckBaseList": true
  of "ckYieldStatement, ckObjectCreationExpression": true
  of "ckYieldStatement, ckLiteralExpression": true
  of "ckStruct, ckTypeParameterList": true
  of "ckStruct, ckEnum": true
  of "ckElseClause, ckExpressionStatement": true
  of "ckStruct, ckConstructor": true
  of "ckElseClause, ckThrowStatement": true
  of "ckInterface, ckProperty": true
  of "ckStruct, ckField": true
  of "ckAwaitExpression, ckParenthesizedExpression": true
  of "ckInterface, ckTypeParameterList": true
  of "ckSwitchStatement, ckMemberAccessExpression": true
  of "ckInterface, ckBaseList": true
  of "ckForEachStatement, ckPredefinedType": true
  of "ckReturnStatement, ckAwaitExpression": true
  of "ckElseClause, ckReturnStatement": true
  of "ckStruct, ckProperty": true
  of "ckBinaryExpression, ckBinaryExpression": true
  of "ckBinaryExpression, ckInvocationExpression": true
  of "ckReturnStatement, ckBinaryExpression": true
  of "ckSimpleBaseType, ckGenericName": true
  of "ckBinaryExpression, ckMemberAccessExpression": true
  of "ckBinaryExpression, ckLiteralExpression": true
  of "ckAssignmentExpression, ckMemberAccessExpression": true
  of "ckClass, ckTypeParameterList": true
  of "ckTypeParameterList, ckTypeParameter": true
  of "ckClass, ckTypeParameterConstraintClause": true
  of "ckTypeParameterConstraintClause, ckTypeConstraint": true
  of "ckTypeConstraint, ckGenericName": true
  of "ckInvocationExpression, ckGenericName": true
  of "ckMethod, ckIfStatement": true
  of "ckIfStatement, ckBinaryExpression": true
  of "ckBinaryExpression, ckTypeOfExpression": true
  of "ckAssignmentExpression, ckCastExpression": true
  of "ckCastExpression, ckThisExpression": true
  of "ckParameter, ckArrayType": true
  of "ckArrayType, ckPredefinedType": true
  of "ckArrayType, ckArrayRankSpecifier": true
  of "ckArrayRankSpecifier, ckOmittedArraySizeExpression": true
  of "ckMethod, ckArrowExpressionClause": true
  of "ckArrowExpressionClause, ckInvocationExpression": true
  of "ckArgument, ckSimpleLambdaExpression": true
  of "ckSimpleLambdaExpression, ckParameter": true
  of "ckIfStatement, ckInvocationExpression": true
  of "ckMethod, ckForStatement": true
  of "ckForStatement, ckVariable": true
  of "ckVariable, ckArrayType": true
  of "ckEqualsValueClause, ckInitializerExpression": true
  of "ckForStatement, ckBinaryExpression": true
  of "ckMethod, ckDoStatement": true
  of "ckForStatement, ckPostfixUnaryExpression": true
  of "ckMemberAccessExpression, ckElementAccessExpression": true
  of "ckElementAccessExpression, ckBracketedArgumentList": true
  of "ckBracketedArgumentList, ckArgument": true
  of "ckIfStatement, ckBreakStatement": true
  of "ckNameEquals, ckPrefixUnaryExpression": true
  of "ckMemberAccessExpression, ckThisExpression": true
  of "ckAssignmentExpression, ckLiteralExpression": true
  of "ckMethod, ckWhileStatement": true
  of "ckWhileStatement, ckBinaryExpression": true
  of "ckExpressionStatement, ckPostfixUnaryExpression": true
  of "ckIfStatement, ckPrefixUnaryExpression": true
  of "ckPrefixUnaryExpression, ckInvocationExpression": true
  of "ckBinaryExpression, ckParenthesizedExpression": true
  of "ckParenthesizedExpression, ckBinaryExpression": true
  of "ckArgument, ckInterpolatedStringExpression": true
  of "ckInterpolatedStringExpression, ckInterpolatedStringText": true
  of "ckMethod, ckArrayType": true
  of "ckIfStatement, ckThrowStatement": true
  of "ckThrowStatement, ckObjectCreationExpression": true
  of "ckArgument, ckConditionalExpression": true
  of "ckConditionalExpression, ckParenthesizedExpression": true
  of "ckConditionalExpression, ckLiteralExpression": true
  of "ckConditionalExpression, ckMemberAccessExpression": true
  of "ckMemberAccessExpression, ckPredefinedType": true
  of "ckEqualsValueClause, ckArrayCreationExpression": true
  of "ckArrayCreationExpression, ckArrayType": true
  of "ckIfStatement, ckExpressionStatement": true
  of "ckAssignmentExpression, ckArrayCreationExpression": true
  of "ckArrayCreationExpression, ckInitializerExpression": true
  of "ckInitializerExpression, ckArrayCreationExpression": true
  of "ckMethod, ckUsingStatement": true
  of "ckUsingStatement, ckVariable": true
  of "ckUsingStatement, ckUsingStatement": true
  of "ckUsingStatement, ckExpressionStatement": true
  of "ckAssignmentExpression, ckInvocationExpression": true
  of "ckElementAccessExpression, ckElementAccessExpression": true
  of "ckArgument, ckParenthesizedLambdaExpression": true
  of "ckParenthesizedLambdaExpression, ckParameterList": true
  of "ckMethod, ckTryStatement": true
  of "ckTryStatement, ckCatchClause": true
  of "ckCatchClause, ckCatch": true
  of "ckAssignmentExpression, ckAssignmentExpression": true
  of "ckAccessor, ckReturnStatement": true
  of "ckReturnStatement, ckElementAccessExpression": true
  of "ckProperty, ckExplicitInterfaceSpecifier": true
  of "ckArrowExpressionClause, ckBinaryExpression": true
  of "ckPrefixUnaryExpression, ckObjectCreationExpression": true
  of "ckMethod, ckThrowStatement": true
  of "ckTypeArgumentList, ckArrayType": true
  of "ckForStatement, ckPrefixUnaryExpression": true
  of "ckParenthesizedLambdaExpression, ckMemberAccessExpression": true
  of "ckSimpleLambdaExpression, ckBinaryExpression": true
  of "ckProperty, ckGenericName": true
  of "ckMemberAccessExpression, ckTypeOfExpression": true
  of "ckSimpleLambdaExpression, ckInvocationExpression": true
  of "ckAssignmentExpression, ckInitializerExpression": true
  of "ckSimpleLambdaExpression, ckAssignmentExpression": true
  of "ckArgument, ckTypeOfExpression": true
  of "ckWhileStatement, ckExpressionStatement": true
  of "ckAccessor, ckArrowExpressionClause": true
  of "ckParenthesizedLambdaExpression, ckCastExpression": true
  of "ckExplicitInterfaceSpecifier, ckGenericName": true
  of "ckReturnStatement, ckPostfixUnaryExpression": true
  of "ckArgument, ckPostfixUnaryExpression": true
  of "ckNamespace, ckExternAliasDirective": true
  of "ckParenthesizedExpression, ckObjectCreationExpression": true
  of "ckSimpleLambdaExpression, ckSimpleLambdaExpression": true
  of "ckParenthesizedExpression, ckArrayCreationExpression": true
  of "ckSimpleBaseType, ckPredefinedType": true
  of "ckSimpleLambdaExpression, ckParenthesizedExpression": true
  of "ckEqualsValueClause, ckAssignmentExpression": true
  of "ckIfStatement, ckParenthesizedExpression": true
  of "ckElementAccessExpression, ckObjectCreationExpression": true
  of "ckInterpolation, ckPrefixUnaryExpression": true
  of "ckBinaryExpression, ckThisExpression": true
  of "ckInvocationExpression, ckLiteralExpression": true
  of "ckSimpleLambdaExpression, ckLiteralExpression": true
  of "ckForStatement, ckIfStatement": true
  of "ckConditionalExpression, ckTypeOfExpression": true
  of "ckAssignmentExpression, ckParenthesizedExpression": true
  of "ckInterpolation, ckLiteralExpression": true
  of "ckIfStatement, ckConditionalExpression": true
  of "ckInterpolation, ckBinaryExpression": true
  of "ckParenthesizedExpression, ckLiteralExpression": true
  of "ckBinaryExpression, ckPostfixUnaryExpression": true
  of "ckTypeOfExpression, ckArrayType": true
  of "ckConditionalExpression, ckInterpolatedStringExpression": true
  of "ckMethod, ckCastExpression": true
  of "ckCastExpression, ckPrefixUnaryExpression": true
  of "ckParenthesizedLambdaExpression, ckParenthesizedLambdaExpression": true
  of "ckPredefinedType, ckGenericName": true
  of "ckMemberAccessExpression, ckArrayCreationExpression": true
  of "ckUsingStatement, ckIfStatement": true
  of "ckElementAccessExpression, ckThisExpression": true
  of "ckParenthesizedLambdaExpression, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckParenthesizedLambdaExpression": true
  of "ckIfStatement, ckIfStatement": true
  of "ckConstructor, ckArrowExpressionClause": true
  of "ckInitializerExpression, ckBinaryExpression": true
  of "ckBinaryExpression, ckArrayType": true
  of "ckThrowStatement, ckLiteralExpression": true
  of "ckUsingStatement, ckAssignmentExpression": true
  of "ckUsingStatement, ckCastExpression": true
  of "ckPrefixUnaryExpression, ckCastExpression": true
  of "ckIfStatement, ckLiteralExpression": true
  of "ckSimpleLambdaExpression, ckPrefixUnaryExpression": true
  of "ckInvocationExpression, ckInvocationExpression": true
  of "ckArgument, ckThisExpression": true
  of "ckEqualsValueClause, ckConditionalExpression": true
  of "ckMemberAccessExpression, ckParenthesizedExpression": true
  of "ckIfStatement, ckMemberAccessExpression": true
  of "ckProperty, ckEqualsValueClause": true
  of "ckProperty, ckLocalDeclarationStatement": true
  of "ckUsingStatement, ckMemberAccessExpression": true
  of "ckInterpolatedStringExpression, ckInterpolation": true
  of "ckInitializerExpression, ckParenthesizedLambdaExpression": true
  of "ckParenthesizedLambdaExpression, ckAssignmentExpression": true
  of "ckEqualsValueClause, ckParenthesizedLambdaExpression": true
  of "ckArgument, ckCastExpression": true
  of "ckArrayRankSpecifier, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckObjectCreationExpression": true
  of "ckAssignmentExpression, ckThisExpression": true
  of "ckBinaryExpression, ckElementAccessExpression": true
  of "ckMethod, ckTypeParameterList": true
  of "ckReturnStatement, ckCastExpression": true
  of "ckAssignmentExpression, ckBinaryExpression": true
  of "ckReturnStatement, ckConditionalExpression": true
  of "ckReturnStatement, ckAssignmentExpression": true
  of "ckParenthesizedLambdaExpression, ckPostfixUnaryExpression": true
  of "ckEqualsValueClause, ckCastExpression": true
  of "ckParenthesizedLambdaExpression, ckObjectCreationExpression": true
  of "ckForStatement, ckForStatement": true
  of "ckAssignmentExpression, ckSimpleLambdaExpression": true
  of "ckBinaryExpression, ckPrefixUnaryExpression": true
  of "ckIfStatement, ckReturnStatement": true
  of "ckParenthesizedLambdaExpression, ckConditionalExpression": true
  of "ckProperty, ckArrayType": true
  of "ckAssignmentExpression, ckParenthesizedLambdaExpression": true
  of "ckCastExpression, ckParenthesizedExpression": true
  of "ckProperty, ckArrowExpressionClause": true
  of "ckBinaryExpression, ckCastExpression": true
  of "ckSimpleLambdaExpression, ckMemberAccessExpression": true
  of "ckConditionalExpression, ckBinaryExpression": true
  of "ckArrowExpressionClause, ckArrayCreationExpression": true
  of "ckCastExpression, ckPredefinedType": true
  of "ckMemberAccessExpression, ckLiteralExpression": true
  of "ckUsingStatement, ckInvocationExpression": true
  of "ckArrowExpressionClause, ckCastExpression": true
  of "ckPrefixUnaryExpression, ckParenthesizedExpression": true
  of "ckExpressionStatement, ckLiteralExpression": true
  of "ckReturnStatement, ckInterpolatedStringExpression": true
  of "ckEnum, ckBaseList": true
  of "ckReturnStatement, ckArrayCreationExpression": true
  of "ckCastExpression, ckInvocationExpression": true
  of "ckMemberAccessExpression, ckInterpolatedStringExpression": true
  of "ckParenthesizedLambdaExpression, ckInvocationExpression": true
  of "ckPostfixUnaryExpression, ckMemberAccessExpression": true
  of "ckMethod, ckExplicitInterfaceSpecifier": true
  of "ckParenthesizedLambdaExpression, ckBinaryExpression": true
  of "ckArgument, ckElementAccessExpression": true
  of "ckArrayType, ckGenericName": true
  of "ckEqualsValueClause, ckPrefixUnaryExpression": true
  of "ckArrowExpressionClause, ckAssignmentExpression": true
  of "ckPrefixUnaryExpression, ckMemberAccessExpression": true
  of "ckArgument, ckArrayCreationExpression": true
  of "ckAssignmentExpression, ckElementAccessExpression": true
  of "ckForStatement, ckExpressionStatement": true
  of "ckArrowExpressionClause, ckMemberAccessExpression": true
  of "ckBinaryExpression, ckGenericName": true
  of "ckWhileStatement, ckInvocationExpression": true
  of "ckEqualsValueClause, ckElementAccessExpression": true
  of "ckAssignmentExpression, ckInterpolatedStringExpression": true
  of "ckParenthesizedExpression, ckPrefixUnaryExpression": true
  of "ckArrowExpressionClause, ckLiteralExpression": true
  of "ckCastExpression, ckMemberAccessExpression": true
  of "ckReturnStatement, ckTypeOfExpression": true
  of "ckInitializerExpression, ckInvocationExpression": true
  of "ckArrowExpressionClause, ckConditionalExpression": true
  of "ckNamespace, ckMethod": true
  of "ckAssignmentExpression, ckConditionalExpression": true
  of "ckEqualsValueClause, ckTypeOfExpression": true
  of "ckForStatement, ckAssignmentExpression": true
  of "ckArrayRankSpecifier, ckBinaryExpression": true
  of "ckAssignmentExpression, ckPrefixUnaryExpression": true
  of "ckSimpleLambdaExpression, ckObjectCreationExpression": true
  of "ckLiteralExpression, ckBinaryExpression": true
  of "ckReturnStatement, ckParenthesizedExpression": true
  of "ckBinaryExpression, ckPredefinedType": true
  of "ckExpressionStatement, ckObjectCreationExpression": true
  of "ckParenthesizedExpression, ckConditionalExpression": true
  of "ckArrowExpressionClause, ckInterpolatedStringExpression": true
  of "ckParenthesizedLambdaExpression, ckPrefixUnaryExpression": true
  of "ckParenthesizedExpression, ckParenthesizedLambdaExpression": true
  of "ckReturnStatement, ckSimpleLambdaExpression": true
  of "ckWhileStatement, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckTypeOfExpression": true
  of "ckReturnStatement, ckPrefixUnaryExpression": true
  of "ckReturnStatement, ckThisExpression": true
  of "ckParenthesizedExpression, ckInvocationExpression": true
  of "ckReturnStatement, ckParenthesizedLambdaExpression": true
  of "ckMethod, ckTypeParameterConstraintClause": true
  of "ckInterpolation, ckMemberAccessExpression": true
  of "ckTypeOfExpression, ckGenericName": true
  of "ckElementAccessExpression, ckInvocationExpression": true
  of "ckCastExpression, ckArrayType": true
  of "ckCastExpression, ckGenericName": true
  of "ckCastExpression, ckLiteralExpression": true
  of "ckConditionalExpression, ckInvocationExpression": true
  of "ckInterpolation, ckInvocationExpression": true
  of "ckBinaryExpression, ckObjectCreationExpression": true
  of "ckElementAccessExpression, ckMemberAccessExpression": true
  of "ckWhileStatement, ckPrefixUnaryExpression": true
  of "ckExpressionStatement, ckPrefixUnaryExpression": true
  of "ckConditionalExpression, ckCastExpression": true
  of "ckEqualsValueClause, ckInterpolatedStringExpression": true
  of "ckParenthesizedExpression, ckAssignmentExpression": true
  of "ckEqualsValueClause, ckSimpleLambdaExpression": true
  of "ckArgument, ckParenthesizedExpression": true
  of "ckParenthesizedExpression, ckMemberAccessExpression": true
  of "ckInvocationExpression, ckElementAccessExpression": true
  of "ckParenthesizedExpression, ckCastExpression": true
  of "ckTypeOfExpression, ckPredefinedType": true
  of "ckInitializerExpression, ckCastExpression": true
  of "ckParenthesizedExpression, ckPostfixUnaryExpression": true
  of "ckElementAccessExpression, ckLiteralExpression": true
  of "ckIfStatement, ckCastExpression": true
  of "ckThrowStatement, ckCastExpression": true
  of "ckConditionalExpression, ckAssignmentExpression": true
  of "ckArrowExpressionClause, ckParenthesizedExpression": true
  of "ckMemberAccessExpression, ckPostfixUnaryExpression": true
  of "ckConditionalExpression, ckParenthesizedLambdaExpression": true
  of "ckConditionalExpression, ckElementAccessExpression": true
  of "ckThrowStatement, ckParenthesizedExpression": true
  of "ckIfStatement, ckTryStatement": true
  of "ckArrowExpressionClause, ckSimpleLambdaExpression": true
  of "ckBinaryExpression, ckArrayCreationExpression": true
  of "ckNamespace, ckConstructor": true
  of "ckArrowExpressionClause, ckElementAccessExpression": true
  of "ckExpressionStatement, ckCastExpression": true
  of "ckNamespace, ckProperty": true
  of "ckSimpleLambdaExpression, ckElementAccessExpression": true
  of "ckParenthesizedExpression, ckElementAccessExpression": true
  of "ckUsingStatement, ckObjectCreationExpression": true
  of "ckForStatement, ckLocalDeclarationStatement": true
  of "ckIndexer, ckArrowExpressionClause": true
  of "ckPrefixUnaryExpression, ckPrefixUnaryExpression": true
  of "ckUsingStatement, ckReturnStatement": true
  of "ckParenthesizedExpression, ckTypeOfExpression": true
  of "ckExpressionStatement, ckElementAccessExpression": true
  of "ckInterpolation, ckParenthesizedExpression": true
  of "ckPrefixUnaryExpression, ckElementAccessExpression": true
  of "ckInitializerExpression, ckElementAccessExpression": true
  of "ckConditionalExpression, ckArrayCreationExpression": true
  of "ckUsingStatement, ckWhileStatement": true
  of "ckInterpolation, ckAssignmentExpression": true
  of "ckCastExpression, ckPostfixUnaryExpression": true
  of "ckUsingStatement, ckConditionalExpression": true
  of "ckDoStatement, ckPrefixUnaryExpression": true
  of "ckParenthesizedLambdaExpression, ckInterpolatedStringExpression": true
  of "ckIfStatement, ckLocalDeclarationStatement": true
  of "ckExpressionStatement, ckMemberAccessExpression": true
  of "ckForStatement, ckMemberAccessExpression": true
  of "ckInterpolation, ckElementAccessExpression": true
  of "ckSimpleLambdaExpression, ckArrayCreationExpression": true
  of "ckUsingStatement, ckBinaryExpression": true
  of "ckCatch, ckGenericName": true
  of "ckPostfixUnaryExpression, ckParenthesizedExpression": true
  of "ckArrayRankSpecifier, ckConditionalExpression": true
  of "ckWhileStatement, ckIfStatement": true
  of "ckParenthesizedLambdaExpression, ckElementAccessExpression": true
  of "ckArrayRankSpecifier, ckInvocationExpression": true
  of "ckParenthesizedExpression, ckInterpolatedStringExpression": true
  of "ckAssignmentExpression, ckPostfixUnaryExpression": true
  of "ckCatch, ckPredefinedType": true
  of "ckInitializerExpression, ckParenthesizedExpression": true
  of "ckSimpleLambdaExpression, ckCastExpression": true
  of "ckParenthesizedExpression, ckParenthesizedExpression": true
  of "ckThrowStatement, ckInvocationExpression": true
  of "ckDoStatement, ckInvocationExpression": true
  of "ckSimpleLambdaExpression, ckInterpolatedStringExpression": true
  of "ckIndexer, ckGenericName": true
  of "ckConditionalExpression, ckConditionalExpression": true
  of "ckArgument, ckPredefinedType": true
  of "ckArgument, ckGenericName": true
  of "ckInitializerExpression, ckInterpolatedStringExpression": true
  of "ckExpressionStatement, ckThisExpression": true
  of "ckForStatement, ckParenthesizedExpression": true
  of "ckArrowExpressionClause, ckPrefixUnaryExpression": true
  of "ckAssignmentExpression, ckTypeOfExpression": true
  of "ckEqualsValueClause, ckPostfixUnaryExpression": true
  of "ckDoStatement, ckBinaryExpression": true
  of "ckIfStatement, ckAssignmentExpression": true
  of "ckInterpolation, ckPostfixUnaryExpression": true
  of "ckWhileStatement, ckForStatement": true
  of "ckForStatement, ckLiteralExpression": true
  of "ckArrayRankSpecifier, ckPrefixUnaryExpression": true
  of "ckVariableDeclarator, ckBracketedArgumentList": true
  of "ckInitializerExpression, ckPostfixUnaryExpression": true
  of "ckWhileStatement, ckElementAccessExpression": true
  of "ckArrayRankSpecifier, ckParenthesizedExpression": true
  of "ckWhileStatement, ckConditionalExpression": true
  of "ckSimpleLambdaExpression, ckPostfixUnaryExpression": true
  of "ckInvocationExpression, ckPredefinedType": true
  of "ckForStatement, ckInvocationExpression": true
  of "ckParenthesizedLambdaExpression, ckArrayCreationExpression": true
  of "ckWhileStatement, ckMemberAccessExpression": true
  of "ckInterpolation, ckTypeOfExpression": true
  of "ckInterpolation, ckCastExpression": true
  of "ckEqualsValueClause, ckThisExpression": true
  of "ckNamespace, ckField": true
  of "ckReturnStatement, ckImplicitArrayCreationExpression": true
  of "ckDelegate, ckParameterList": true
  of "ckArgument, ckAnonymousMethodExpression": true
  of "ckTypeArgumentList, ckNullableType": true
  of "ckBinaryExpression, ckConditionalAccessExpression": true
  of "ckArgument, ckNameColon": true
  of "ckBinaryExpression, ckAwaitExpression": true
  of "ckProperty, ckNullableType": true
  of "ckMethod, ckForEachStatement": true
  of "ckDelegate, ckGenericName": true
  of "ckArgument, ckImplicitArrayCreationExpression": true
  of "ckVariable, ckNullableType": true
  of "ckEqualsValueClause, ckImplicitArrayCreationExpression": true
  of "ckIfStatement, ckElseClause": true
  of "ckClass, ckDelegate": true
  of "ckAssignmentExpression, ckAwaitExpression": true
  of "ckParenthesizedLambdaExpression, ckAwaitExpression": true
  of "ckExpressionStatement, ckAwaitExpression": true
  of "ckMemberAccessExpression, ckBaseExpression": true
  of "ckEqualsValueClause, ckAnonymousMethodExpression": true
  of "ckInvocationExpression, ckCheckedExpression": true
  of "ckMethod, ckNullableType": true
  of "ckEqualsValueClause, ckCheckedExpression": true
  of "ckMethod, ckSwitchStatement": true
  of "ckArgument, ckBaseExpression": true
  of "ckArrowExpressionClause, ckConditionalAccessExpression": true
  of "ckTryStatement, ckFinallyClause": true
  of "ckAssignmentExpression, ckAnonymousMethodExpression": true
  of "ckDelegate, ckPredefinedType": true
  of "ckEqualsValueClause, ckConditionalAccessExpression": true
  of "ckElementAccessExpression, ckBaseExpression": true
  of "ckEqualsValueClause, ckAwaitExpression": true
  of "ckBinaryExpression, ckCheckedExpression": true
  of "ckParameter, ckNullableType": true
  of "ckNamespace, ckInterface": true
  of "ckClass, ckInterface": true
  of "ckMethod, ckYieldStatement": true
  of "ckArrowExpressionClause, ckImplicitArrayCreationExpression": true
  of "ckCastExpression, ckNullableType": true
  of "ckElementAccessExpression, ckPredefinedType": true
  of "ckArrowExpressionClause, ckPostfixUnaryExpression": true
  of "ckIfStatement, ckUsingStatement": true
  of "ckInterpolation, ckObjectCreationExpression": true
  of "ckInvocationExpression, ckParenthesizedLambdaExpression": true
  of "ckBinaryExpression, ckInterpolatedStringExpression": true
  of "ckPostfixUnaryExpression, ckLiteralExpression": true
  of "ckThrowStatement, ckMemberAccessExpression": true
  of "ckCastExpression, ckArrayCreationExpression": true
  of "ckDoStatement, ckLiteralExpression": true
  of "ckCatch, ckArrayType": true
  of "ckArrayRankSpecifier, ckCastExpression": true
  of "ckClass, ckGenericName": true
  of "ckIfStatement, ckForStatement": true
  of "ckInitializerExpression, ckThisExpression": true
  of "ckInvocationExpression, ckParenthesizedExpression": true
  of "ckExpressionStatement, ckBinaryExpression": true
  of "ckArrowExpressionClause, ckThisExpression": true
  of "ckSimpleBaseType, ckArrayType": true
  of "ckArrowExpressionClause, ckThrowExpression": true
  of "ckIfStatement, ckForEachStatement": true
  of "ckEqualsValueClause, ckDefaultExpression": true
  of "ckAssignmentExpression, ckDefaultExpression": true
  of "ckParameter, ckPointerType": true
  of "ckParenthesizedExpression, ckIsPatternExpression": true
  of "ckClass, ckIncompleteMember": true
  of "ckArgument, ckAnonymousObjectCreationExpression": true
  of "ckMethod, ckPointerType": true
  of "ckAssignmentExpression, ckConditionalAccessExpression": true
  of "ckInterpolation, ckInterpolationFormatClause": true
  of "ckReturnStatement, ckCheckedExpression": true
  of "ckSimpleLambdaExpression, ckAnonymousObjectCreationExpression": true
  of "ckSimpleBaseType, ckAliasQualifiedName": true
  of "ckDelegate, ckTypeParameterList": true
  of "ckArrayType, ckNullableType": true
  of "ckCastExpression, ckPointerType": true
  of "ckUsingStatement, ckEmptyStatement": true
  of "ckNamespace, ckIncompleteMember": true
  of "ckReturnStatement, ckConditionalAccessExpression": true
  of "ckArgument, ckDefaultExpression": true
  of "ckCastExpression, ckAwaitExpression": true
  of "ckWhileStatement, ckEmptyStatement": true
  of "ckIfStatement, ckEmptyStatement": true
  of "ckTypeArgumentList, ckOmittedTypeArgument": true
  of "ckArrayType, ckTupleType": true
  of "ckUsingStatement, ckAwaitExpression": true
  of "ckVariable, ckAliasQualifiedName": true
  of "ckArgument, ckCheckedExpression": true
  of "ckBinaryExpression, ckNullableType": true
  of "ckReturnStatement, ckSwitchExpression": true
  of "ckParenthesizedLambdaExpression, ckAnonymousObjectCreationExpression": true
  of "ckArgument, ckIsPatternExpression": true
  of "ckArrowExpressionClause, ckAwaitExpression": true
  of "ckUsingStatement, ckConditionalAccessExpression": true
  of "ckMethod, ckContinueStatement": true
  of "ckTypeOfExpression, ckPointerType": true
  of "ckAssignmentExpression, ckCheckedExpression": true
  of "ckArgument, ckImplicitObjectCreationExpression": true
  of "ckArgument, ckConditionalAccessExpression": true
  of "ckAssignmentExpression, ckImplicitObjectCreationExpression": true
  of "ckConditionalExpression, ckDefaultExpression": true
  of "ckSwitchStatement, ckInvocationExpression": true
  of "ckIsPatternExpression, ckConstantPattern": true
  of "ckCheckedExpression, ckCastExpression": true
  of "ckSwitchStatement, ckSwitchSection": true
  of "ckTupleType, ckTupleElement": true
  of "ckDeclarationExpression, ckSingleVariableDesignation": true
  of "ckQueryExpression, ckQueryBody": true
  of "ckIsPatternExpression, ckDeclarationPattern": true
  of "ckConditionalAccessExpression, ckMemberAccessExpression": true
  of "ckImplicitElementAccess, ckBracketedArgumentList": true
  of "ckStruct, ckIncompleteMember": true
  of "ckEqualsValueClause, ckRefExpression": true
  of "ckDeclarationExpression, ckPredefinedType": true
  of "ckYieldStatement, ckInvocationExpression": true
  of "ckConditionalAccessExpression, ckMemberBindingExpression": true
  of "ckParenthesizedLambdaExpression, ckThrowExpression": true
  of "ckStruct, ckMethod": true
  of "ckForEachStatement, ckThisExpression": true
  of "ckAnonymousObjectCreationExpression, ckAnonymousObjectMemberDeclarator": true
  of "ckSwitchStatement, ckCastExpression": true
  of "ckEqualsValueClause, ckImplicitObjectCreationExpression": true
  of "ckConditionalAccessExpression, ckParenthesizedExpression": true
  of "ckConditionalAccessExpression, ckConditionalAccessExpression": true
  of "ckReturnStatement, ckQueryExpression": true
  of "ckTypeOfExpression, ckNullableType": true
  of "ckIsPatternExpression, ckMemberAccessExpression": true
  of "ckForEachStatement, ckArrayCreationExpression": true
  of "ckDefaultExpression, ckPredefinedType": true
  of "ckAnonymousMethodExpression, ckParameterList": true
  of "ckCheckedExpression, ckBinaryExpression": true
  of "ckForStatement, ckYieldStatement": true
  of "ckForEachStatement, ckImplicitArrayCreationExpression": true
  of "ckForEachStatement, ckGenericName": true
  of "ckParenthesizedExpression, ckImplicitArrayCreationExpression": true
  of "ckForEachStatement, ckObjectCreationExpression": true
  of "ckDeclarationExpression, ckParenthesizedVariableDesignation": true
  of "ckMethod, ckRefType": true
  of "ckMethod, ckGotoStatement": true
  of "ckAwaitExpression, ckMemberAccessExpression": true
  of "ckConditionalExpression, ckConditionalAccessExpression": true
  of "ckParenthesizedLambdaExpression, ckConditionalAccessExpression": true
  of "ckArrowExpressionClause, ckQueryExpression": true
  of "ckSwitchStatement, ckConditionalAccessExpression": true
  of "ckDeclarationExpression, ckNullableType": true
  of "ckIndexer, ckNullableType": true
  of "ckStruct, ckDelegate": true
  of "ckParenthesizedLambdaExpression, ckRefExpression": true
  of "ckForEachStatement, ckYieldStatement": true
  of "ckReturnStatement, ckDefaultExpression": true
  of "ckWhileStatement, ckIsPatternExpression": true
  of "ckLockStatement, ckMemberAccessExpression": true
  of "ckArgument, ckQueryExpression": true
  of "ckConditionalExpression, ckImplicitArrayCreationExpression": true
  of "ckYieldStatement, ckMemberAccessExpression": true
  of "ckSimpleLambdaExpression, ckThrowExpression": true
  of "ckPointerType, ckPointerType": true
  of "ckIsPatternExpression, ckUnaryPattern": true
  of "ckEqualsValueClause, ckStackAllocArrayCreationExpression": true
  of "ckSwitchStatement, ckPrefixUnaryExpression": true
  of "ckParenthesizedExpression, ckCheckedExpression": true
  of "ckForEachStatement, ckPostfixUnaryExpression": true
  of "ckMemberAccessExpression, ckImplicitArrayCreationExpression": true
  of "ckSwitchStatement, ckBinaryExpression": true
  of "ckForEachStatement, ckArrayType": true
  of "ckEqualsValueClause, ckIsPatternExpression": true
  of "ckEqualsValueClause, ckTupleExpression": true
  of "ckEqualsValueClause, ckSwitchExpression": true
  of "ckForEachStatement, ckIfStatement": true
  of "ckIfStatement, ckGotoStatement": true
  of "ckInterface, ckIndexer": true
  of "ckYieldStatement, ckInterpolatedStringExpression": true
  of "ckEqualsValueClause, ckMakeRefExpression": true
  of "ckInitializerExpression, ckAwaitExpression": true
  of "ckIndexer, ckRefType": true
  of "ckCatchClause, ckCatchFilterClause": true
  of "ckConditionalExpression, ckIsPatternExpression": true
  of "ckArgument, ckRangeExpression": true
  of "ckArgument, ckAliasQualifiedName": true
  of "ckForEachStatement, ckCastExpression": true
  of "ckYieldStatement, ckBinaryExpression": true
  of "ckArrowExpressionClause, ckSwitchExpression": true
  of "ckDeclarationExpression, ckGenericName": true
  of "ckSwitchStatement, ckElementAccessExpression": true
  of "ckSwitchStatement, ckLiteralExpression": true
  of "ckSimpleLambdaExpression, ckImplicitArrayCreationExpression": true
  of "ckInitializerExpression, ckImplicitArrayCreationExpression": true
  of "ckLockStatement, ckTypeOfExpression": true
  of "ckMemberAccessExpression, ckAnonymousObjectCreationExpression": true
  of "ckLockStatement, ckLockStatement": true
  of "ckArgument, ckTupleExpression": true
  of "ckInitializerExpression, ckDefaultExpression": true
  of "ckAssignmentExpression, ckTupleExpression": true
  of "ckForStatement, ckUsingStatement": true
  of "ckSwitchStatement, ckAwaitExpression": true
  of "ckBinaryExpression, ckDefaultExpression": true
  of "ckDeclarationExpression, ckDiscardDesignation": true
  of "ckTypeParameterConstraintClause, ckClassOrStructConstraint": true
  of "ckInitializerExpression, ckCheckedExpression": true
  of "ckInterface, ckField": true
  of "ckReturnStatement, ckAnonymousObjectCreationExpression": true
  of "ckArrowExpressionClause, ckIsPatternExpression": true
  of "ckAssignmentExpression, ckSwitchExpression": true
  of "ckElementAccessExpression, ckDefaultExpression": true
  of "ckIncompleteMember, ckGenericName": true
  of "ckObjectCreationExpression, ckNullableType": true
  of "ckParenthesizedLambdaExpression, ckAnonymousMethodExpression": true
  of "ckReturnStatement, ckTupleExpression": true
  of "ckPostfixUnaryExpression, ckDefaultExpression": true
  of "ckArrowExpressionClause, ckRefExpression": true
  of "ckInterpolation, ckConditionalAccessExpression": true
  of "ckObjectCreationExpression, ckAliasQualifiedName": true
  of "ckArrowExpressionClause, ckImplicitObjectCreationExpression": true
  of "ckVariable, ckTupleType": true
  of "ckArgumentList, ckGenericName": true
  of "ckAssignmentExpression, ckAnonymousObjectCreationExpression": true
  of "ckDeclarationExpression, ckArrayType": true
  of "ckParenthesizedLambdaExpression, ckQueryExpression": true
  of "ckYieldStatement, ckParenthesizedExpression": true
  of "ckProperty, ckRefType": true
  of "ckParenthesizedExpression, ckConditionalAccessExpression": true
  of "ckBinaryExpression, ckAnonymousMethodExpression": true
  of "ckConditionalAccessExpression, ckElementBindingExpression": true
  of "ckForStatement, ckSwitchStatement": true
  of "ckInitializerExpression, ckAnonymousObjectCreationExpression": true
  of "ckIsPatternExpression, ckRecursivePattern": true
  of "ckInvocationExpression, ckAliasQualifiedName": true
  of "ckLockStatement, ckExpressionStatement": true
  of "ckForEachStatement, ckSwitchStatement": true
  of "ckThrowExpression, ckInvocationExpression": true
  of "ckElementAccessExpression, ckParenthesizedLambdaExpression": true
  of "ckIsPatternExpression, ckInvocationExpression": true
  of "ckSimpleLambdaExpression, ckTupleExpression": true
  of "ckForEachStatement, ckParenthesizedExpression": true
  of "ckArrayType, ckPointerType": true
  of "ckIfStatement, ckAwaitExpression": true
  of "ckReturnStatement, ckAnonymousMethodExpression": true
  of "ckExpressionStatement, ckQueryExpression": true
  of "ckForEachStatement, ckForEachStatement": true
  of "ckCastExpression, ckBaseExpression": true
  of "ckTupleElement, ckPredefinedType": true
  of "ckForEachStatement, ckBinaryExpression": true
  of "ckParameter, ckTupleType": true
  of "ckProperty, ckInvocationExpression": true
  of "ckYieldStatement, ckThisExpression": true
  of "ckDeclarationPattern, ckSingleVariableDesignation": true
  of "ckCheckedExpression, ckInvocationExpression": true
  of "ckCastExpression, ckTypeOfExpression": true
  of "ckForStatement, ckLockStatement": true
  of "ckDeclarationPattern, ckPredefinedType": true
  of "ckBinaryExpression, ckImplicitArrayCreationExpression": true
  of "ckTypeConstraint, ckArrayType": true
  of "ckMemberAccessExpression, ckElementBindingExpression": true
  of "ckTupleElement, ckArrayType": true
  of "ckYieldStatement, ckPrefixUnaryExpression": true
  of "ckForEachStatement, ckConditionalAccessExpression": true
  of "ckArgument, ckWithExpression": true
  of "ckYieldStatement, ckCastExpression": true
  of "ckConditionalExpression, ckThrowExpression": true
  of "ckConditionalExpression, ckCheckedExpression": true
  of "ckIncompleteMember, ckTupleType": true
  of "ckSwitchStatement, ckThisExpression": true
  of "ckWhileStatement, ckParenthesizedExpression": true
  of "ckDelegate, ckRefType": true
  of "ckInitializerExpression, ckAnonymousMethodExpression": true
  of "ckSimpleLambdaExpression, ckIsPatternExpression": true
  of "ckInitializerExpression, ckImplicitObjectCreationExpression": true
  of "ckIfStatement, ckLockStatement": true
  of "ckIsPatternExpression, ckCastExpression": true
  of "ckSimpleLambdaExpression, ckConditionalAccessExpression": true
  of "ckDefaultExpression, ckNullableType": true
  of "ckAwaitExpression, ckDefaultExpression": true
  of "ckElementAccessExpression, ckImplicitArrayCreationExpression": true
  of "ckTupleElement, ckTupleType": true
  of "ckYieldStatement, ckConditionalExpression": true
  of "ckMemberAccessExpression, ckDefaultExpression": true
  of "ckInitializerExpression, ckTupleExpression": true
  of "ckLockStatement, ckAssignmentExpression": true
  of "ckAssignmentExpression, ckBaseExpression": true
  of "ckForStatement, ckCheckedStatement": true
  of "ckRefType, ckPredefinedType": true
  of "ckStruct, ckStruct": true
  of "ckForEachStatement, ckAnonymousMethodExpression": true
  of "ckAwaitExpression, ckObjectCreationExpression": true
  of "ckCastExpression, ckAnonymousMethodExpression": true
  of "ckReturnStatement, ckRefExpression": true
  of "ckAwaitExpression, ckLiteralExpression": true
  of "ckAwaitExpression, ckConditionalAccessExpression": true
  of "ckForEachStatement, ckLiteralExpression": true
  of "ckDelegate, ckPointerType": true
  of "ckElseClause, ckWhileStatement": true
  of "ckSimpleLambdaExpression, ckImplicitObjectCreationExpression": true
  of "ckSimpleLambdaExpression, ckDefaultExpression": true
  of "ckYieldStatement, ckImplicitArrayCreationExpression": true
  of "ckConditionalAccessExpression, ckLiteralExpression": true
  of "ckSwitchSection, ckCaseSwitchLabel": true
  of "ckInterpolation, ckThisExpression": true
  of "ckLockStatement, ckReturnStatement": true
  of "ckUsingStatement, ckTryStatement": true
  of "ckYieldStatement, ckElementAccessExpression": true
  of "ckDoStatement, ckMemberAccessExpression": true
  of "ckDelegate, ckArrayType": true
  of "ckIndexer, ckPointerType": true
  of "ckArrowExpressionClause, ckCheckedExpression": true
  of "ckTupleElement, ckNullableType": true
  of "ckAwaitExpression, ckCheckedExpression": true
  of "ckLockStatement, ckLiteralExpression": true
  of "ckParenthesizedLambdaExpression, ckParenthesizedExpression": true
  of "ckInterface, ckClass": true
  of "ckParenthesizedLambdaExpression, ckDefaultExpression": true
  of "ckRefType, ckGenericName": true
  of "ckArrowExpressionClause, ckWithExpression": true
  of "ckSimpleLambdaExpression, ckAwaitExpression": true
  of "ckConstantPattern, ckLiteralExpression": true
  of "ckReturnStatement, ckIsPatternExpression": true
  of "ckYieldStatement, ckTypeOfExpression": true
  of "ckParenthesizedExpression, ckAnonymousMethodExpression": true
  of "ckNullableType, ckTupleType": true
  of "ckCastExpression, ckImplicitArrayCreationExpression": true
  of "ckAssignmentExpression, ckQueryExpression": true
  of "ckParenthesizedLambdaExpression, ckTupleExpression": true
  of "ckForEachStatement, ckEmptyStatement": true
  of "ckInterface, ckIncompleteMember": true
  of "ckStruct, ckClass": true
  of "ckElseClause, ckForStatement": true
  of "ckMethod, ckAliasQualifiedName": true
  of "ckBinaryExpression, ckTupleExpression": true
  of "ckConditionalExpression, ckSimpleLambdaExpression": true
  of "ckWhileStatement, ckAwaitExpression": true
  of "ckThrowStatement, ckThisExpression": true
  of "ckLockStatement, ckInvocationExpression": true
  of "ckPrefixUnaryExpression, ckAwaitExpression": true
  of "ckQueryBody, ckLetClause": true
  of "ckSimpleLambdaExpression, ckSwitchExpression": true
  of "ckElseClause, ckYieldStatement": true
  of "ckDefaultExpression, ckGenericName": true
  of "ckLockStatement, ckEmptyStatement": true
  of "ckArgument, ckRefValueExpression": true
  of "ckTypeArgumentList, ckAliasQualifiedName": true
  of "ckElseClause, ckSwitchStatement": true
  of "ckInterpolation, ckInterpolationAlignmentClause": true
  of "ckForEachStatement, ckUsingStatement": true
  of "ckInvocationExpression, ckMemberBindingExpression": true
  of "ckProperty, ckPointerType": true
  of "ckIfStatement, ckSwitchStatement": true
  of "ckCastExpression, ckCheckedExpression": true
  of "ckYieldStatement, ckDefaultExpression": true
  of "ckArrayRankSpecifier, ckElementAccessExpression": true
  of "ckForEachStatement, ckAwaitExpression": true
  of "ckUsingStatement, ckForStatement": true
  of "ckThrowExpression, ckLiteralExpression": true
  of "ckTypeArgumentList, ckPointerType": true
  of "ckConditionalAccessExpression, ckElementAccessExpression": true
  of "ckTupleElement, ckGenericName": true
  of "ckIsPatternExpression, ckElementAccessExpression": true
  of "ckStruct, ckTypeParameterConstraintClause": true
  of "ckWhileStatement, ckYieldStatement": true
  of "ckLockStatement, ckElementAccessExpression": true
  of "ckBinaryExpression, ckBaseExpression": true
  of "ckUsingStatement, ckFixedStatement": true
  of "ckConstructor, ckInvocationExpression": true
  of "ckForEachStatement, ckReturnStatement": true
  of "ckThrowExpression, ckObjectCreationExpression": true
  of "ckTypeParameterConstraintClause, ckConstructorConstraint": true
  of "ckMemberAccessExpression, ckTupleExpression": true
  of "ckDeclarationPattern, ckGenericName": true
  of "ckProperty, ckTupleType": true
  of "ckForEachStatement, ckElementAccessExpression": true
  of "ckStruct, ckIndexer": true
  of "ckArrayRankSpecifier, ckCheckedExpression": true
  of "ckCheckedExpression, ckParenthesizedExpression": true
  of "ckForEachStatement, ckQueryExpression": true
  of "ckConditionalAccessExpression, ckThisExpression": true
  of "ckNamespace, ckAliasQualifiedName": true
  of "ckLockStatement, ckObjectCreationExpression": true
  of "ckInterpolation, ckAwaitExpression": true
  of "ckSwitchSection, ckCasePatternSwitchLabel": true
  of "ckForStatement, ckWhileStatement": true
  of "ckParenthesizedExpression, ckThisExpression": true
  of "ckElseClause, ckBreakStatement": true
  of "ckTypeConstraint, ckPredefinedType": true
  of "ckMemberAccessExpression, ckMemberBindingExpression": true
  of "ckInitializerExpression, ckConditionalAccessExpression": true
  of "ckDelegate, ckNullableType": true
  of "ckElseClause, ckContinueStatement": true
  of "ckArgument, ckThrowExpression": true
  of "ckSwitchSection, ckDefaultSwitchLabel": true
  of "ckInterface, ckTypeParameterConstraintClause": true
  of "ckTupleExpression, ckArgument": true
  of "ckPrefixUnaryExpression, ckConditionalAccessExpression": true
  of "ckArgument, ckSwitchExpression": true
  of "ckElseClause, ckEmptyStatement": true
  of "ckForStatement, ckIsPatternExpression": true
  of "ckForStatement, ckForEachStatement": true
  of "ckParenthesizedLambdaExpression, ckIsPatternExpression": true
  of "ckConditionalExpression, ckPostfixUnaryExpression": true
  of "ckObjectCreationExpression, ckTupleType": true
  of "ckAwaitExpression, ckAwaitExpression": true
  of "ckDeclarationPattern, ckArrayType": true
  of "ckEqualsValueClause, ckRefValueExpression": true
  of "ckGotoStatement, ckLiteralExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckNameEquals": true
  of "ckArgument, ckOmittedArraySizeExpression": true
  of "ckIncompleteMember, ckPredefinedType": true
  of "ckPrefixUnaryExpression, ckThisExpression": true
  of "ckIsPatternExpression, ckLiteralExpression": true
  of "ckStackAllocArrayCreationExpression, ckArrayType": true
  of "ckStackAllocArrayCreationExpression, ckPredefinedType": true
  of "ckParenthesizedVariableDesignation, ckSingleVariableDesignation": true
  of "ckAnonymousObjectMemberDeclarator, ckObjectCreationExpression": true
  of "ckDelegate, ckTypeParameterConstraintClause": true
  of "ckCatchFilterClause, ckLiteralExpression": true
  of "ckCaseSwitchLabel, ckLiteralExpression": true
  of "ckRefExpression, ckElementAccessExpression": true
  of "ckRefExpression, ckConditionalExpression": true
  of "ckInterpolationAlignmentClause, ckInvocationExpression": true
  of "ckCatchFilterClause, ckAwaitExpression": true
  of "ckCatchFilterClause, ckInvocationExpression": true
  of "ckRefExpression, ckLiteralExpression": true
  of "ckElementBindingExpression, ckBracketedArgumentList": true
  of "ckAliasQualifiedName, ckGenericName": true
  of "ckInterpolationAlignmentClause, ckMemberAccessExpression": true
  of "ckCaseSwitchLabel, ckMemberAccessExpression": true
  of "ckCheckedExpression, ckAnonymousMethodExpression": true
  of "ckForEachStatement, ckNullableType": true
  of "ckCatchFilterClause, ckBinaryExpression": true
  of "ckConstantPattern, ckPrefixUnaryExpression": true
  of "ckRefExpression, ckMemberAccessExpression": true
  of "ckInterpolationAlignmentClause, ckLiteralExpression": true
  of "ckSwitchSection, ckBreakStatement": true
  of "ckAnonymousObjectMemberDeclarator, ckLiteralExpression": true
  of "ckSwitchSection, ckGotoStatement": true
  of "ckSwitchSection, ckExpressionStatement": true
  of "ckSwitchSection, ckLabeledStatement": true
  of "ckAnonymousObjectMemberDeclarator, ckAnonymousMethodExpression": true
  of "ckSwitchSection, ckThrowStatement": true
  of "ckConstantPattern, ckBinaryExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckSimpleLambdaExpression": true
  of "ckSwitchSection, ckReturnStatement": true
  of "ckAnonymousObjectMemberDeclarator, ckTupleExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckInvocationExpression": true
  of "ckConditionalExpression, ckRefExpression": true
  of "ckSwitchSection, ckLocalDeclarationStatement": true
  of "ckLabeledStatement, ckBreakStatement": true
  of "ckAnonymousObjectMemberDeclarator, ckBinaryExpression": true
  of "ckUnaryPattern, ckConstantPattern": true
  of "ckSwitchSection, ckIfStatement": true
  of "ckInvocationExpression, ckBaseExpression": true
  of "ckInitializerExpression, ckThrowExpression": true
  of "ckRefExpression, ckInvocationExpression": true
  of "ckCaseSwitchLabel, ckInvocationExpression": true
  of "ckCasePatternSwitchLabel, ckDeclarationPattern": true
  of "ckRangeExpression, ckElementAccessExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckMemberAccessExpression": true
  of "ckSwitchSection, ckForEachStatement": true
  of "ckSwitchSection, ckTryStatement": true
  of "ckMemberBindingExpression, ckGenericName": true
  of "ckSwitchExpression, ckSwitchExpressionArm": true
  of "ckAnonymousObjectMemberDeclarator, ckImplicitArrayCreationExpression": true
  of "ckImplicitObjectCreationExpression, ckArgumentList": true
  of "ckAnonymousObjectMemberDeclarator, ckAnonymousObjectCreationExpression": true
  of "ckYieldStatement, ckTupleExpression": true
  of "ckSwitchSection, ckSwitchStatement": true
  of "ckParenthesizedVariableDesignation, ckDiscardDesignation": true
  of "ckCaseSwitchLabel, ckCheckedExpression": true
  of "ckDeclarationPattern, ckDiscardDesignation": true
  of "ckIncompleteMember, ckArrayType": true
  of "ckCaseSwitchLabel, ckCastExpression": true
  of "ckSwitchSection, ckForStatement": true
  of "ckSwitchExpressionArm, ckDeclarationPattern": true
  of "ckLetClause, ckInvocationExpression": true
  of "ckInterface, ckInterface": true
  of "ckPrefixUnaryExpression, ckPostfixUnaryExpression": true
  of "ckBinaryExpression, ckRangeExpression": true
  of "ckIncompleteMember, ckPointerType": true
  of "ckSwitchSection, ckUsingStatement": true
  of "ckRangeExpression, ckLiteralExpression": true
  of "ckCatchFilterClause, ckPrefixUnaryExpression": true
  of "ckSwitchExpressionArm, ckConstantPattern": true
  of "ckSwitchExpressionArm, ckBinaryPattern": true
  of "ckSwitchSection, ckContinueStatement": true
  of "ckSwitchExpression, ckMemberAccessExpression": true
  of "ckArrowExpressionClause, ckTupleExpression": true
  of "ckLetClause, ckQueryExpression": true
  of "ckCasePatternSwitchLabel, ckConstantPattern": true
  of "ckUnaryPattern, ckDeclarationPattern": true
  of "ckAwaitExpression, ckPostfixUnaryExpression": true
  of "ckConstantPattern, ckMemberAccessExpression": true
  of "ckCaseSwitchLabel, ckPrefixUnaryExpression": true
  of "ckYieldStatement, ckPostfixUnaryExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckDefaultExpression": true
  of "ckForStatement, ckContinueStatement": true
  of "ckInvocationExpression, ckPostfixUnaryExpression": true
  of "ckIsPatternExpression, ckParenthesizedExpression": true
  of "ckElementAccessExpression, ckArrayCreationExpression": true
  of "ckSwitchSection, ckLockStatement": true
  of "ckStackAllocArrayCreationExpression, ckInitializerExpression": true
  of "ckDeclarationExpression, ckPointerType": true
  of "ckCheckedExpression, ckPrefixUnaryExpression": true
  of "ckRefExpression, ckBinaryExpression": true
  of "ckRangeExpression, ckParenthesizedExpression": true
  of "ckMemberAccessExpression, ckRefValueExpression": true
  of "ckLabeledStatement, ckGotoStatement": true
  of "ckRefExpression, ckThisExpression": true
  of "ckInterface, ckDelegate": true
  of "ckInterface, ckEnum": true
  of "ckPointerType, ckGenericName": true
  of "ckInterface, ckStruct": true
  of "ckSimpleBaseType, ckPointerType": true
  of "ckCastExpression, ckDefaultExpression": true
  of "ckSimpleBaseType, ckNullableType": true
  of "ckInterface, ckConstructor": true
  of "ckSwitchSection, ckYieldStatement": true
  of "ckAnonymousObjectMemberDeclarator, ckCastExpression": true
  of "ckParameter, ckAliasQualifiedName": true
  of "ckIndexer, ckArrayType": true
  of "ckNamespace, ckIndexer": true
  of "ckIfStatement, ckCheckedExpression": true
  of "ckLockStatement, ckIfStatement": true
  of "ckEqualsValueClause, ckRefTypeExpression": true
  of "ckSwitchStatement, ckDefaultExpression": true
  of "ckDefaultExpression, ckArrayType": true
  of "ckCaseSwitchLabel, ckParenthesizedExpression": true
  of "ckElseClause, ckLocalDeclarationStatement": true
  of "ckAnonymousObjectMemberDeclarator, ckArrayCreationExpression": true
  of "ckConstantPattern, ckDefaultExpression": true
  of "ckRefExpression, ckPrefixUnaryExpression": true
  of "ckLetClause, ckMemberAccessExpression": true
  of "ckRefType, ckPointerType": true
  of "ckThrowStatement, ckConditionalExpression": true
  of "ckExplicitInterfaceSpecifier, ckAliasQualifiedName": true
  of "ckCheckedExpression, ckLiteralExpression": true
  of "ckCastExpression, ckTupleExpression": true
  of "ckArrowExpressionClause, ckDefaultExpression": true
  of "ckPrefixUnaryExpression, ckPredefinedType": true
  of "ckSwitchExpression, ckTupleExpression": true
  of "ckElseClause, ckGotoStatement": true
  of "ckSwitchExpressionArm, ckInvocationExpression": true
  of "ckForEachStatement, ckTupleType": true
  of "ckSwitchExpressionArm, ckMemberAccessExpression": true
  of "ckInterpolation, ckInterpolatedStringExpression": true
  of "ckOmittedTypeArgument, ckGenericName": true
  of "ckPostfixUnaryExpression, ckConditionalAccessExpression": true
  of "ckRangeExpression, ckCastExpression": true
  of "ckSwitchSection, ckWhileStatement": true
  of "ckSwitchSection, ckEmptyStatement": true
  of "ckSwitchExpressionArm, ckThrowExpression": true
  of "ckRangeExpression, ckInvocationExpression": true
  of "ckCasePatternSwitchLabel, ckWhenClause": true
  of "ckCaseSwitchLabel, ckBinaryExpression": true
  of "ckIncompleteMember, ckRefType": true
  of "ckConditionalExpression, ckStackAllocArrayCreationExpression": true
  of "ckLabeledStatement, ckExpressionStatement": true
  of "ckSwitchExpressionArm, ckLiteralExpression": true
  of "ckGotoStatement, ckMemberAccessExpression": true
  of "ckEqualsValueClause, ckGenericName": true
  of "ckWhileStatement, ckAssignmentExpression": true
  of "ckSwitchExpressionArm, ckInterpolatedStringExpression": true
  of "ckCheckedExpression, ckConditionalExpression": true
  of "ckCasePatternSwitchLabel, ckVarPattern": true
  of "ckSwitchSection, ckDoStatement": true
  of "ckLetClause, ckConditionalExpression": true
  of "ckRecursivePattern, ckPropertyPatternClause": true
  of "ckParenthesizedLambdaExpression, ckImplicitArrayCreationExpression": true
  of "ckForStatement, ckThrowStatement": true
  of "ckInterpolationAlignmentClause, ckPrefixUnaryExpression": true
  of "ckRefValueExpression, ckPredefinedType": true
  of "ckRecursivePattern, ckPositionalPatternClause": true
  of "ckSwitchExpressionArm, ckCastExpression": true
  of "ckRefValueExpression, ckInvocationExpression": true
  of "ckSwitchExpressionArm, ckDiscardPattern": true
  of "ckThrowExpression, ckParenthesizedExpression": true
  of "ckElementAccessExpression, ckPostfixUnaryExpression": true
  of "ckUsingStatement, ckLocalDeclarationStatement": true
  of "ckAssignmentExpression, ckStackAllocArrayCreationExpression": true
  of "ckWhenClause, ckParenthesizedExpression": true
  of "ckThrowStatement, ckPostfixUnaryExpression": true
  of "ckParameter, ckFunctionPointerType": true
  of "ckSwitchExpression, ckInvocationExpression": true
  of "ckConditionalExpression, ckTupleExpression": true
  of "ckSwitchExpressionArm, ckPrefixUnaryExpression": true
  of "ckWhenClause, ckBinaryExpression": true
  of "ckSwitchExpression, ckElementAccessExpression": true
  of "ckSwitchExpression, ckParenthesizedExpression": true
  of "ckFixedStatement, ckVariable": true
  of "ckWithExpression, ckMemberAccessExpression": true
  of "ckSwitchExpressionArm, ckRecursivePattern": true
  of "ckTypeOfExpression, ckAliasQualifiedName": true
  of "ckSwitchExpressionArm, ckParenthesizedExpression": true
  of "ckAssignmentExpression, ckRefValueExpression": true
  of "ckSwitchExpressionArm, ckConditionalExpression": true
  of "ckWithExpression, ckInitializerExpression": true
  of "ckPropertyPatternClause, ckSubpattern": true
  of "ckMemberAccessExpression, ckRefTypeExpression": true
  of "ckPositionalPatternClause, ckSubpattern": true
  of "ckWhenClause, ckIsPatternExpression": true
  of "ckBinaryPattern, ckBinaryPattern": true
  of "ckBinaryExpression, ckRefTypeExpression": true
  of "ckWhileStatement, ckBreakStatement": true
  of "ckWhileStatement, ckCastExpression": true
  of "ckForStatement, ckElementAccessExpression": true
  of "ckForStatement, ckCastExpression": true
  of "ckWhileStatement, ckWhileStatement": true
  of "ckSwitchExpressionArm, ckImplicitArrayCreationExpression": true
  of "ckElementAccessExpression, ckMemberBindingExpression": true
  of "ckSwitchExpressionArm, ckObjectCreationExpression": true
  of "ckRefValueExpression, ckParenthesizedExpression": true
  of "ckWhileStatement, ckCheckedExpression": true
  of "ckArrowExpressionClause, ckAnonymousMethodExpression": true
  of "ckConditionalExpression, ckMakeRefExpression": true
  of "ckWhileStatement, ckReturnStatement": true
  of "ckElementAccessExpression, ckRefValueExpression": true
  of "ckArgument, ckMakeRefExpression": true
  of "ckForStatement, ckObjectCreationExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckInterpolatedStringExpression": true
  of "ckRangeExpression, ckMemberAccessExpression": true
  of "ckAssignmentExpression, ckIsPatternExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckElementAccessExpression": true
  of "ckDoStatement, ckIsPatternExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckConditionalExpression": true
  of "ckSubpattern, ckConstantPattern": true
  of "ckConstantPattern, ckInvocationExpression": true
  of "ckElseClause, ckLockStatement": true
  of "ckPostfixUnaryExpression, ckTupleExpression": true
  of "ckConstructor, ckIfStatement": true
  of "ckInterface, ckEventField": true
  of "ckMethod, ckLiteralExpression": true
  of "ckConstructor, ckUsingStatement": true
  of "ckAccessor, ckLockStatement": true
  of "ckNameEquals, ckLiteralExpression": true
  of "ckClass, ckEvent": true
  of "ckConstructor, ckThrowStatement": true
  of "ckClass, ckLiteralExpression": true
  of "ckParameter, ckLiteralExpression": true
  of "ckAccessor, ckIfStatement": true
  of "ckAccessor, ckYieldStatement": true
  of "ckConstructor, ckForEachStatement": true
  of "ckExpressionStatement, ckExpressionStatement": true
  of "ckInterface, ckLiteralExpression": true
  of "ckUsingDirective, ckLiteralExpression": true
  of "ckClass, ckEventField": true
  of "ckConstructor, ckTryStatement": true
  of "ckAccessor, ckThrowStatement": true
  of "ckSubpattern, ckDiscardPattern": true
  of "ckConstructor, ckForStatement": true
  of "ckProperty, ckLiteralExpression": true
  of "ckEvent, ckAccessorList": true
  of "ckAccessor, ckWhileStatement": true
  of "ckPredefinedType, ckLiteralExpression": true
  of "ckEventField, ckVariable": true
  of "ckConstructor, ckWhileStatement": true
  of "ckStruct, ckEventField": true
  of "ckField, ckLiteralExpression": true
  of "ckAccessor, ckUsingStatement": true
  of "ckStruct, ckLiteralExpression": true
  of "ckAccessor, ckTryStatement": true
  of "ckConstructor, ckLiteralExpression": true
  of "ckAccessor, ckForStatement": true
  of "ckEnum, ckLiteralExpression": true
  of "ckSwitchExpressionArm, ckBinaryExpression": true
  of "ckDoStatement, ckExpressionStatement": true
  of "ckEvent, ckGenericName": true
  of "ckCheckedExpression, ckArrayCreationExpression": true
  of "ckAccessor, ckCastExpression": true
  of "ckAccessor, ckForEachStatement": true
  of "ckEvent, ckNullableType": true
  of "ckConstructor, ckLockStatement": true
  of "ckThrowExpression, ckBinaryExpression": true
  of "ckConstructor, ckContinueStatement": true
  of "ckEvent, ckExplicitInterfaceSpecifier": true
  of "ckClass, ckDestructor": true
  of "ckClass, ckOperator": true
  of "ckClass, ckConversionOperator": true
  of "ckStruct, ckOperator": true
  of "ckAwaitExpression, ckCastExpression": true
  of "ckAccessor, ckDoStatement": true
  of "ckThrowStatement, ckElementAccessExpression": true
  of "ckConstructor, ckDoStatement": true
  of "ckAssignmentExpression, ckRefExpression": true
  of "ckConditionalAccessExpression, ckTypeOfExpression": true
  of "ckConversionOperator, ckParameterList": true
  of "ckDestructor, ckParameterList": true
  of "ckConversionOperator, ckPredefinedType": true
  of "ckOperator, ckParameterList": true
  of "ckInvocationExpression, ckObjectCreationExpression": true
  of "ckWhenClause, ckInvocationExpression": true
  of "ckConversionOperator, ckPointerType": true
  of "ckOperator, ckGenericName": true
  of "ckConversionOperator, ckArrayType": true
  of "ckStruct, ckConversionOperator": true
  of "ckYieldStatement, ckParenthesizedLambdaExpression": true
  of "ckSwitchSection, ckForEachVariableStatement": true
  of "ckOperator, ckPredefinedType": true
  of "ckDelegate, ckTupleType": true
  of "ckAccessor, ckContinueStatement": true
  of "ckPostfixUnaryExpression, ckPostfixUnaryExpression": true
  of "ckIsPatternExpression, ckThisExpression": true
  of "ckEventField, ckLiteralExpression": true
  of "ckBinaryExpression, ckSizeOfExpression": true
  of "ckEvent, ckLiteralExpression": true
  of "ckConversionOperator, ckArrowExpressionClause": true
  of "ckOperator, ckArrowExpressionClause": true
  of "ckConversionOperator, ckGenericName": true
  of "ckIfStatement, ckWhileStatement": true
  of "ckSizeOfExpression, ckPredefinedType": true
  of "ckIsPatternExpression, ckBinaryExpression": true
  of "ckReturnStatement, ckSizeOfExpression": true
  of "ckStruct, ckDestructor": true
  of "ckInterface, ckEvent": true
  of "ckAssignmentExpression, ckSizeOfExpression": true
  of "ckDestructor, ckArrowExpressionClause": true
  of "ckConstructor, ckYieldStatement": true
  of "ckConversionOperator, ckNullableType": true
  of "ckTypeParameter, ckLiteralExpression": true
  of "ckInterface, ckOperator": true
  of "ckArgument, ckSizeOfExpression": true
  of "ckEqualsValueClause, ckSizeOfExpression": true
  of "ckOperator, ckReturnStatement": true
  of "ckConversionOperator, ckReturnStatement": true
  of "ckIfStatement, ckObjectCreationExpression": true
  of "ckSwitchStatement, ckObjectCreationExpression": true
  of "ckCastExpression, ckSizeOfExpression": true
  of "ckPostfixUnaryExpression, ckThisExpression": true
  of "ckSwitchExpressionArm, ckArrayCreationExpression": true
  of "ckOperator, ckNullableType": true
  of "ckPrefixUnaryExpression, ckCheckedExpression": true
  of "ckTypeOfExpression, ckTupleType": true
  of "ckSubpattern, ckNameColon": true
  of "ckSizeOfExpression, ckPointerType": true
  of "ckArrowExpressionClause, ckSizeOfExpression": true
  of "ckArrayRankSpecifier, ckSizeOfExpression": true
  of "ckForStatement, ckAwaitExpression": true
  of "ckIncompleteMember, ckNullableType": true
  of "ckDelegate, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckAnonymousObjectCreationExpression": true
  of "ckConditionalExpression, ckGenericName": true
  of "ckInterpolation, ckSizeOfExpression": true
  of "ckSubpattern, ckDeclarationPattern": true
  of "ckBinaryExpression, ckSwitchExpression": true
  of "ckWhenClause, ckPrefixUnaryExpression": true
  of "ckSubpattern, ckUnaryPattern": true
  of "ckAnonymousObjectMemberDeclarator, ckPrefixUnaryExpression": true
  of "ckSwitchExpressionArm, ckVarPattern": true
  of "ckForEachStatement, ckTryStatement": true
  of "ckAwaitExpression, ckElementAccessExpression": true
  of "ckSwitchExpressionArm, ckElementAccessExpression": true
  of "ckWithExpression, ckInvocationExpression": true
  of "ckAccessor, ckGotoStatement": true
  of "ckSwitchExpressionArm, ckRelationalPattern": true
  of "ckRangeExpression, ckPrefixUnaryExpression": true
  of "ckThrowStatement, ckBinaryExpression": true
  of "ckIsPatternExpression, ckDefaultExpression": true
  of "ckForEachStatement, ckRefType": true
  of "ckSubpattern, ckRecursivePattern": true
  of "ckAccessor, ckLiteralExpression": true
  of "ckCasePatternSwitchLabel, ckRecursivePattern": true
  of "ckMemberAccessExpression, ckStackAllocArrayCreationExpression": true
  of "ckElseClause, ckForEachStatement": true
  of "ckSwitchExpressionArm, ckWhenClause": true
  of "ckReturnStatement, ckImplicitObjectCreationExpression": true
  of "ckDefaultExpression, ckTupleType": true
  of "ckConditionalExpression, ckSwitchExpression": true
  of "ckTypeArgumentList, ckRefType": true
  of "ckIndexer, ckLiteralExpression": true
  of "ckLabeledStatement, ckEmptyStatement": true
  of "ckIfStatement, ckCheckedStatement": true
  of "ckIsPatternExpression, ckVarPattern": true
  of "ckArrayRankSpecifier, ckPredefinedType": true
  of "ckConditionalExpression, ckAnonymousMethodExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckConditionalAccessExpression": true
  of "ckImplicitObjectCreationExpression, ckInitializerExpression": true
  of "ckParenthesizedLambdaExpression, ckSimpleLambdaExpression": true
  of "ckBinaryPattern, ckTypePattern": true
  of "ckSwitchSection, ckCheckedStatement": true
  of "ckAwaitExpression, ckThisExpression": true
  of "ckCatchFilterClause, ckIsPatternExpression": true
  of "ckUsingStatement, ckUnsafeStatement": true
  of "ckConstructor, ckCastExpression": true
  of "ckConstructor, ckGotoStatement": true
  of "ckInitializerExpression, ckSizeOfExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckTypeOfExpression": true
  of "ckSwitchStatement, ckParenthesizedExpression": true
  of "ckExpressionStatement, ckIsPatternExpression": true
  of "ckForEachStatement, ckConditionalExpression": true
  of "ckConstantPattern, ckIsPatternExpression": true
  of "ckThrowExpression, ckMemberAccessExpression": true
  of "ckForStatement, ckPredefinedType": true
  of "ckRefType, ckNullableType": true
  of "ckSwitchExpression, ckTypeOfExpression": true
  of "ckParenthesizedExpression, ckSwitchExpression": true
  of "ckForStatement, ckTryStatement": true
  of "ckAwaitExpression, ckInterpolatedStringExpression": true
  of "ckCaseSwitchLabel, ckSizeOfExpression": true
  of "ckExpressionStatement, ckTupleExpression": true
  of "ckNamespace, ckEventField": true
  of "ckSwitchStatement, ckAssignmentExpression": true
  of "ckCatchFilterClause, ckMemberAccessExpression": true
  of "ckRefType, ckArrayType": true
  of "ckSwitchExpressionArm, ckIsPatternExpression": true
  of "ckConversionOperator, ckTupleType": true
  of "ckLetClause, ckBinaryExpression": true
  of "ckCheckedExpression, ckPostfixUnaryExpression": true
  of "ckStruct, ckInterface": true
  of "ckParenthesizedExpression, ckSizeOfExpression": true
  of "ckSwitchExpressionArm, ckAwaitExpression": true
  of "ckSwitchExpression, ckConditionalAccessExpression": true
  of "ckIndexer, ckTupleType": true
  of "ckYieldStatement, ckAssignmentExpression": true
  of "ckForStatement, ckUnsafeStatement": true
  of "ckCastExpression, ckTupleType": true
  of "ckArgument, ckStackAllocArrayCreationExpression": true
  of "ckOmittedArraySizeExpression, ckGenericName": true
  of "ckSwitchExpression, ckThisExpression": true
  of "ckSimpleLambdaExpression, ckParenthesizedLambdaExpression": true
  of "ckInitializerExpression, ckGenericName": true
  of "ckLetClause, ckImplicitArrayCreationExpression": true
  of "ckDeclarationExpression, ckTupleType": true
  of "ckExpressionStatement, ckParenthesizedExpression": true
  of "ckSimpleLambdaExpression, ckTypeOfExpression": true
  of "ckLetClause, ckCastExpression": true
  of "ckParenthesizedLambdaExpression, ckThisExpression": true
  of "ckSwitchExpressionArm, ckTypeOfExpression": true
  of "ckTypeConstraint, ckNullableType": true
  of "ckConstantPattern, ckElementAccessExpression": true
  of "ckConstantPattern, ckCastExpression": true
  of "ckRecursivePattern, ckSingleVariableDesignation": true
  of "ckSwitchStatement, ckPostfixUnaryExpression": true
  of "ckParenthesizedVariableDesignation, ckParenthesizedVariableDesignation": true
  of "ckConditionalExpression, ckSizeOfExpression": true
  of "ckStruct, ckEvent": true
  of "ckVarPattern, ckSingleVariableDesignation": true
  of "ckSubpattern, ckRelationalPattern": true
  of "ckRelationalPattern, ckLiteralExpression": true
  of "ckInvocationExpression, ckSimpleLambdaExpression": true
  of "ckArrayRankSpecifier, ckAssignmentExpression": true
  of "ckForEachStatement, ckForStatement": true
  of "ckCheckedExpression, ckImplicitArrayCreationExpression": true
  of "ckIsPatternExpression, ckAwaitExpression": true
  of "ckElseClause, ckUsingStatement": true
  of "ckInitializerExpression, ckBaseExpression": true
  of "ckThrowStatement, ckSwitchExpression": true
  of "ckForEachStatement, ckThrowStatement": true
  of "ckParenthesizedExpression, ckDefaultExpression": true
  of "ckOperator, ckPointerType": true
  of "ckExpressionStatement, ckConditionalExpression": true
  of "ckElseClause, ckTryStatement": true
  of "ckSwitchStatement, ckBaseExpression": true
  of "ckWhileStatement, ckTryStatement": true
  of "ckUsingStatement, ckThrowStatement": true
  of "ckYieldStatement, ckSimpleLambdaExpression": true
  of "ckSimpleLambdaExpression, ckCheckedExpression": true
  of "ckDoStatement, ckAwaitExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckParenthesizedExpression": true
  of "ckForEachVariableStatement, ckDeclarationExpression": true
  of "ckWhileStatement, ckCheckedStatement": true
  of "ckUsingStatement, ckLockStatement": true
  of "ckAssignmentExpression, ckPredefinedType": true
  of "ckArrayRankSpecifier, ckRangeExpression": true
  of "ckLockStatement, ckForEachStatement": true
  of "ckWhenClause, ckMemberAccessExpression": true
  of "ckParenthesizedExpression, ckRangeExpression": true
  of "ckTryStatement, ckBreakStatement": true
  of "ckConversionOperator, ckLocalDeclarationStatement": true
  of "ckAccessor, ckLocalDeclarationStatement": true
  of "ckSubpattern, ckBinaryPattern": true
  of "ckMethod, ckBreakStatement": true
  of "ckBinaryPattern, ckRecursivePattern": true
  of "ckQueryExpression, ckFromClause": true
  of "ckFromClause, ckMemberAccessExpression": true
  of "ckFromClause, ckLiteralExpression": true
  of "ckFromClause, ckInvocationExpression": true
  of "ckQueryBody, ckSelectClause": true
  of "ckFromClause, ckAwaitExpression": true
  of "ckSelectClause, ckTupleExpression": true
  of "ckSelectClause, ckArrayCreationExpression": true
  of "ckSelectClause, ckConditionalExpression": true
  of "ckQueryBody, ckJoinClause": true
  of "ckSelectClause, ckAnonymousObjectCreationExpression": true
  of "ckSelectClause, ckMemberAccessExpression": true
  of "ckQueryBody, ckWhereClause": true
  of "ckQueryBody, ckFromClause": true
  of "ckQueryBody, ckOrderByClause": true
  of "ckJoinClause, ckInvocationExpression": true
  of "ckSelectClause, ckCastExpression": true
  of "ckWhereClause, ckBinaryExpression": true
  of "ckWhereClause, ckInvocationExpression": true
  of "ckSelectClause, ckInvocationExpression": true
  of "ckOrderByClause, ckOrdering": true
  of "ckFromClause, ckArrayCreationExpression": true
  of "ckSelectClause, ckBinaryExpression": true
  of "ckQueryBody, ckGroupClause": true
  of "ckFromClause, ckPredefinedType": true
  of "ckSelectClause, ckInterpolatedStringExpression": true
  of "ckFromClause, ckImplicitArrayCreationExpression": true
  of "ckGroupClause, ckMemberAccessExpression": true
  of "ckGroupClause, ckAnonymousObjectCreationExpression": true
  of "ckSelectClause, ckObjectCreationExpression": true
  of "ckQueryBody, ckQueryContinuation": true
  of "ckQueryContinuation, ckQueryBody": true
  of "ckWhereClause, ckPrefixUnaryExpression": true
  of "ckGroupClause, ckLiteralExpression": true
  of "ckOrdering, ckMemberAccessExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckQueryExpression": true
  of "ckSelectClause, ckLiteralExpression": true
  of "ckGroupClause, ckBinaryExpression": true
  of "ckWhereClause, ckParenthesizedExpression": true
  of "ckFromClause, ckThisExpression": true
  of "ckOrdering, ckElementAccessExpression": true
  of "ckWhereClause, ckMemberAccessExpression": true
  of "ckSelectClause, ckQueryExpression": true
  of "ckGroupClause, ckInvocationExpression": true
  of "ckOrdering, ckBinaryExpression": true
  of "ckJoinClause, ckMemberAccessExpression": true
  of "ckLetClause, ckLiteralExpression": true
  of "ckJoinClause, ckJoinIntoClause": true
  of "ckTypePattern, ckPredefinedType": true
  of "ckDoStatement, ckConditionalExpression": true
  of "ckFromClause, ckElementAccessExpression": true
  of "ckFromClause, ckQueryExpression": true
  of "ckWhileStatement, ckContinueStatement": true
  of "ckGotoStatement, ckCastExpression": true
  of "ckJoinClause, ckArrayCreationExpression": true
  of "ckSelectClause, ckElementAccessExpression": true
  of "ckPointerType, ckTupleType": true
  of "ckJoinClause, ckLiteralExpression": true
  of "ckFromClause, ckParenthesizedExpression": true
  of "ckElseClause, ckCheckedStatement": true
  of "ckVariable, ckFunctionPointerType": true
  of "ckSwitchExpressionArm, ckTupleExpression": true
  of "ckLetClause, ckArrayCreationExpression": true
  of "ckFromClause, ckConditionalExpression": true
  of "ckFromClause, ckNullableType": true
  of "ckLetClause, ckObjectCreationExpression": true
  of "ckOrdering, ckInvocationExpression": true
  of "ckLetClause, ckElementAccessExpression": true
  of "ckLetClause, ckAnonymousObjectCreationExpression": true
  of "ckParenthesizedExpression, ckAnonymousObjectCreationExpression": true
  of "ckExpressionStatement, ckBaseExpression": true
  of "ckGroupClause, ckCastExpression": true
  of "ckNamespace, ckEvent": true
  of "ckNamespace, ckConversionOperator": true
  of "ckWhereClause, ckIsPatternExpression": true
  of "ckSelectClause, ckImplicitArrayCreationExpression": true
  of "ckRefExpression, ckPostfixUnaryExpression": true
  of "ckLetClause, ckTypeOfExpression": true
  of "ckParenthesizedLambdaExpression, ckCheckedExpression": true
  of "ckParenthesizedExpression, ckGenericName": true
  of "ckOrdering, ckParenthesizedExpression": true
  of "ckDestructor, ckLocalDeclarationStatement": true
  of "ckAnonymousMethodExpression, ckLocalDeclarationStatement": true
  of "ckAnonymousMethodExpression, ckReturnStatement": true
  of "ckConversionOperator, ckThrowStatement": true
  of "ckAccessor, ckSwitchStatement": true
  of "ckParenthesizedLambdaExpression, ckIfStatement": true
  of "ckParenthesizedLambdaExpression, ckLocalDeclarationStatement": true
  of "ckDestructor, ckThrowStatement": true
  of "ckParenthesizedLambdaExpression, ckTryStatement": true
  of "ckTryStatement, ckReturnStatement": true
  of "ckConversionOperator, ckYieldStatement": true
  of "ckConstructor, ckSwitchStatement": true
  of "ckParenthesizedLambdaExpression, ckReturnStatement": true
  of "ckGlobalStatement, ckLocalDeclarationStatement": true
  of "ckMethod, ckCheckedStatement": true
  of "ckMethod, ckLabeledStatement": true
  of "ckGlobalStatement, ckExpressionStatement": true
  of "ckLabeledStatement, ckReturnStatement": true
  of "ckForEachStatement, ckCheckedStatement": true
  of "ckParenthesizedLambdaExpression, ckLabeledStatement": true
  of "ckIfStatement, ckDoStatement": true
  of "ckParenthesizedExpression, ckPredefinedType": true
  of "ckGlobalStatement, ckEmptyStatement": true
  of "ckGlobalStatement, ckLocalFunctionStatement": true
  of "ckIfStatement, ckLabeledStatement": true
  of "ckGlobalStatement, ckTryStatement": true
  of "ckAnonymousMethodExpression, ckGotoStatement": true
  of "ckForStatement, ckGotoStatement": true
  of "ckForEachStatement, ckLocalDeclarationStatement": true
  of "ckParenthesizedLambdaExpression, ckUsingStatement": true
  of "ckGlobalStatement, ckLabeledStatement": true
  of "ckExpressionStatement, ckParenthesizedLambdaExpression": true
  of "ckForStatement, ckReturnStatement": true
  of "ckGlobalStatement, ckUsingStatement": true
  of "ckTryStatement, ckTryStatement": true
  of "ckExpressionStatement, ckArrayCreationExpression": true
  of "ckLabeledStatement, ckIfStatement": true
  of "ckGlobalStatement, ckReturnStatement": true
  of "ckLocalFunctionStatement, ckParameterList": true
  of "ckConstructor, ckCheckedStatement": true
  of "ckAnonymousMethodExpression, ckSwitchStatement": true
  of "ckElseClause, ckLabeledStatement": true
  of "ckParenthesizedLambdaExpression, ckSwitchStatement": true
  of "ckAccessor, ckCheckedStatement": true
  of "ckDestructor, ckLockStatement": true
  of "ckTryStatement, ckUsingStatement": true
  of "ckTryStatement, ckLocalDeclarationStatement": true
  of "ckTryStatement, ckGotoStatement": true
  of "ckLocalFunctionStatement, ckTupleType": true
  of "ckOperator, ckLocalDeclarationStatement": true
  of "ckLabeledStatement, ckThrowStatement": true
  of "ckLocalFunctionStatement, ckPredefinedType": true
  of "ckAnonymousMethodExpression, ckLabeledStatement": true
  of "ckLabeledStatement, ckSwitchStatement": true
  of "ckLabeledStatement, ckLocalDeclarationStatement": true
  of "ckGlobalStatement, ckIfStatement": true
  of "ckTryStatement, ckCheckedStatement": true
  of "ckParenthesizedLambdaExpression, ckWhileStatement": true
  of "ckTryStatement, ckWhileStatement": true
  of "ckLocalFunctionStatement, ckGenericName": true
  of "ckLabeledStatement, ckWhileStatement": true
  of "ckForStatement, ckDoStatement": true
  of "ckForEachStatement, ckDoStatement": true
  of "ckElseClause, ckDoStatement": true
  of "ckTryStatement, ckSwitchStatement": true
  of "ckLabeledStatement, ckLabeledStatement": true
  of "ckForStatement, ckLabeledStatement": true
  of "ckTryStatement, ckLabeledStatement": true
  of "ckCheckedExpression, ckAnonymousObjectCreationExpression": true
  of "ckLocalFunctionStatement, ckArrowExpressionClause": true
  of "ckLabeledStatement, ckTryStatement": true
  of "ckLabeledStatement, ckForEachVariableStatement": true
  of "ckConversionOperator, ckSwitchStatement": true
  of "ckForEachVariableStatement, ckMemberAccessExpression": true
  of "ckCastExpression, ckInterpolatedStringExpression": true
  of "ckJoinClause, ckPredefinedType": true
  of "ckParenthesizedLambdaExpression, ckLockStatement": true
  of "ckForEachStatement, ckWhileStatement": true
  of "ckRefType, ckTupleType": true
  of "ckTryStatement, ckLockStatement": true
  of "ckGlobalStatement, ckForEachStatement": true
  of "ckBinaryPattern, ckConstantPattern": true
  of "ckOperator, ckCheckedStatement": true
  of "ckLabeledStatement, ckForStatement": true
  of "ckProperty, ckAliasQualifiedName": true
  of "ckGlobalStatement, ckBreakStatement": true
  of "ckExpressionStatement, ckRangeExpression": true
  of "ckAnonymousObjectMemberDeclarator, ckCheckedExpression": true
  of "ckGlobalStatement, ckForEachVariableStatement": true
  of "ckParenthesizedLambdaExpression, ckDoStatement": true
  of "ckArrayType, ckAliasQualifiedName": true
  of "ckConstructor, ckLabeledStatement": true
  of "ckForEachStatement, ckLockStatement": true
  of "ckTryStatement, ckDoStatement": true
  of "ckInitializerExpression, ckPredefinedType": true
  of "ckJoinClause, ckAnonymousObjectCreationExpression": true
  of "ckGlobalStatement, ckForStatement": true
  of "ckExpressionStatement, ckAnonymousMethodExpression": true
  of "ckAnonymousMethodExpression, ckWhileStatement": true
  of "ckRefValueExpression, ckMakeRefExpression": true
  of "ckWhileStatement, ckThrowStatement": true
  of "ckFunctionPointerType, ckParameter": true
  of "ckDoStatement, ckElementAccessExpression": true
  of "ckExpressionStatement, ckImplicitArrayCreationExpression": true
  of "ckMakeRefExpression, ckElementAccessExpression": true
  of "ckAssignmentExpression, ckMakeRefExpression": true
  of "ckAnonymousMethodExpression, ckUsingStatement": true
  of "ckBinaryExpression, ckRefValueExpression": true
  of "ckUsingStatement, ckForEachStatement": true
  of "ckRefValueExpression, ckArrayType": true
  of "ckInterpolation, ckPredefinedType": true
  of "ckIsPatternExpression, ckBinaryPattern": true
  of "ckDoStatement, ckCastExpression": true
  of "ckDoStatement, ckParenthesizedExpression": true
  of "ckDoStatement, ckCheckedExpression": true
  of "ckMakeRefExpression, ckMemberAccessExpression": true
  of "ckFromClause, ckConditionalAccessExpression": true
  of "ckSwitchExpressionArm, ckSimpleLambdaExpression": true
  of "ckConditionalExpression, ckRefValueExpression": true
  of "ckAnonymousMethodExpression, ckLockStatement": true
  of "ckSwitchExpressionArm, ckPostfixUnaryExpression": true
  of "ckThrowExpression, ckPostfixUnaryExpression": true
  of "ckCaseSwitchLabel, ckDefaultExpression": true
  of "ckSwitchStatement, ckTupleExpression": true
  of "ckBinaryPattern, ckUnaryPattern": true
  of "ckSwitchExpressionArm, ckSwitchExpression": true
  of "ckProperty, ckReturnStatement": true
  of "ckUnaryPattern, ckRecursivePattern": true
  of "ckSwitchExpressionArm, ckCheckedExpression": true
  of "ckBinaryPattern, ckRelationalPattern": true
  of "ckGroupClause, ckParenthesizedExpression": true
  of "ckIndexer, ckReturnStatement": true
  of "ckLockStatement, ckPostfixUnaryExpression": true
  of "ckFromClause, ckArrayType": true
  of "ckSwitchSection, ckLocalFunctionStatement": true
  of "ckSwitchExpression, ckCheckedExpression": true
  of "ckIndexer, ckLockStatement": true
  of "ckParenthesizedLambdaExpression, ckThrowStatement": true
  of "ckTryStatement, ckThrowStatement": true
  of "ckOperator, ckThrowStatement": true
  of "ckGlobalStatement, ckThrowStatement": true
  of "ckVarPattern, ckDiscardDesignation": true
  of "ckCastExpression, ckFunctionPointerType": true
  of "ckForEachStatement, ckContinueStatement": true
  of "ckLabeledStatement, ckForEachStatement": true
  of "ckForStatement, ckRangeExpression": true
  of "ckForStatement, ckImplicitArrayCreationExpression": true
  of "ckProperty, ckForStatement": true
  of "ckProperty, ckWhileStatement": true
  of "ckDestructor, ckIfStatement": true
  of "ckProperty, ckTryStatement": true
  of "ckProperty, ckThrowStatement": true
  of "ckDestructor, ckTryStatement": true
  of "ckProperty, ckIfStatement": true
  of "ckConversionOperator, ckIfStatement": true
  of "ckProperty, ckForEachStatement": true
  of "ckOperator, ckIfStatement": true
  of "ckProperty, ckDoStatement": true
  of "ckProperty, ckLockStatement": true
  of "ckProperty, ckUsingStatement": true
  of "ckAnonymousMethodExpression, ckIfStatement": true
  of "ckLetClause, ckConditionalAccessExpression": true
  of "ckParenthesizedLambdaExpression, ckForEachStatement": true
  of "ckIndexer, ckSwitchStatement": true
  of "ckIndexer, ckForEachStatement": true
  of "ckProperty, ckSwitchStatement": true
  of "ckProperty, ckCheckedStatement": true
  of "ckIndexer, ckIfStatement": true
  of "ckIndexer, ckLocalDeclarationStatement": true
  of "ckDestructor, ckUsingStatement": true
  of "ckProperty, ckGotoStatement": true
  of "ckAnonymousMethodExpression, ckTryStatement": true
  of "ckTryStatement, ckIfStatement": true
  of "ckNamespace, ckOperator": true
  of "ckYieldStatement, ckAnonymousObjectCreationExpression": true
  of "ckGlobalStatement, ckSwitchStatement": true
  of "ckIndexer, ckThrowStatement": true
  of "ckDestructor, ckForStatement": true
  of "ckConversionOperator, ckTryStatement": true
  of "ckParenthesizedLambdaExpression, ckForStatement": true
  of "ckProperty, ckLabeledStatement": true
  of "ckIndexer, ckForStatement": true
  of "ckConversionOperator, ckForEachStatement": true
  of "ckInvocationExpression, ckThisExpression": true
  of "ckDestructor, ckReturnStatement": true
  of "ckAnonymousMethodExpression, ckForEachStatement": true
  of "ckAnonymousMethodExpression, ckThrowStatement": true
  of "ckDestructor, ckForEachStatement": true
  of "ckConstructor, ckFixedStatement": true
  of "ckMethod, ckFixedStatement": true
  of "ckConversionOperator, ckUnsafeStatement": true
  of "ckConstructor, ckUnsafeStatement": true
  of "ckMethod, ckUnsafeStatement": true
  of "ckProperty, ckYieldStatement": true
  of "ckDefaultExpression, ckPointerType": true
  of "ckLocalFunctionStatement, ckReturnStatement": true
  of "ckFixedStatement, ckExpressionStatement": true
  of "ckMethod, ckForEachVariableStatement": true
  of "ckFixedStatement, ckFixedStatement": true
  of "ckClass, ckLocalDeclarationStatement": true
  of "ckOperator, ckUnsafeStatement": true
  of "ckLabeledStatement, ckYieldStatement": true
  of "ckForEachVariableStatement, ckTupleExpression": true
  of "ckForEachVariableStatement, ckExpressionStatement": true
  of "ckLocalDeclarationStatement, ckLocalFunctionStatement": true
  of "ckMethod, ckLocalFunctionStatement": true
  of "ckProperty, ckFixedStatement": true
  of "ckFixedStatement, ckReturnStatement": true
  of "ckIndexer, ckFixedStatement": true
  of "ckForEachVariableStatement, ckObjectCreationExpression": true
  of "ckProperty, ckUnsafeStatement": true
  of "ckForEachVariableStatement, ckInvocationExpression": true
  of "ckIfStatement, ckFixedStatement": true
  of "ckSimpleLambdaExpression, ckReturnStatement": true
  of "ckSimpleLambdaExpression, ckIfStatement": true
  of "ckLocalFunctionStatement, ckIfStatement": true
  of "ckConstructor, ckForEachVariableStatement": true
  of "ckLocalFunctionStatement, ckTypeParameterList": true
  of "ckLocalFunctionStatement, ckForStatement": true
  of "ckSimpleLambdaExpression, ckForEachStatement": true
  of "ckAccessor, ckLocalFunctionStatement": true
  of "ckConstructor, ckLocalFunctionStatement": true
  of "ckSimpleLambdaExpression, ckThrowStatement": true
  of "ckLocalFunctionStatement, ckTypeParameterConstraintClause": true
  of "ckProperty, ckForEachVariableStatement": true
  of "ckSimpleLambdaExpression, ckUsingStatement": true
  of "ckIndexer, ckWhileStatement": true
  of "ckConversionOperator, ckForStatement": true
  of "ckFixedStatement, ckForStatement": true
  of "ckSimpleLambdaExpression, ckTryStatement": true
  of "ckForEachVariableStatement, ckElementAccessExpression": true
  of "ckReturnStatement, ckBaseExpression": true
  of "ckFixedStatement, ckIfStatement": true
  of "ckParenthesizedLambdaExpression, ckCheckedStatement": true
  of "ckCatchClause, ckContinueStatement": true
  of "ckLocalFunctionStatement, ckArrayType": true
  of "ckReturnStatement, ckRefValueExpression": true
  of "ckDoStatement, ckContinueStatement": true
  of "ckLocalFunctionStatement, ckNullableType": true
  of "ckLocalFunctionStatement, ckRefType": true
  of "ckRelationalPattern, ckParenthesizedExpression": true
  of "ckUnaryPattern, ckParenthesizedPattern": true
  of "ckSelectClause, ckParenthesizedExpression": true
  of "ckJoinClause, ckParenthesizedExpression": true
  of "ckParenthesizedPattern, ckBinaryPattern": true
  of "ckSimpleLambdaExpression, ckForStatement": true
  of "ckArrayRankSpecifier, ckObjectCreationExpression": true
  of "ckForEachVariableStatement, ckLiteralExpression": true
  of "ckSwitchExpressionArm, ckConditionalAccessExpression": true
  of "ckSimpleLambdaExpression, ckLockStatement": true
  else: raise newException(Exception, "cfits is missing:  of \"" & $parent.kind & ", " & $item.kind & "\": true")