import construct, constructs/justtypes
proc cfits*(parent, item: Construct; data: AllNeededData): bool = # asks the inner types to implement fits for these type arguments.
  result = case $parent.kind & ", " & $item.kind
  of "ckNamespace, ckClass": true
  of "ckParenthesizedExpression, ckAwaitExpression": true
  of "ckMemberAccessExpression, ckAliasQualifiedName": true
  of "ckClass, ckField": true
  of "ckNamespace, ckDelegate": true
  of "ckParenthesizedExpression, ckSimpleLambdaExpression": true
  of "ckNamespace, ckEnum": true
  of "ckEnum, ckEnumMember": true
  of "ckClass, ckMethod": true
  of "ckMethod, ckParameterList": true
  of "ckMethod, ckPredefinedType": true
  of "ckMethod, ckLocalDeclarationStatement": true
  of "ckMethod, ckReturnStatement": true
  of "ckEnumMember, ckEqualsValueClause": true
  of "ckEnumMember, ckLiteralExpression": true
  of "ckReturnStatement, ckLiteralExpression": true
  of "ckParameterList, ckParameter": true
  of "ckClass, ckBaseList": true
  of "ckClass, ckSimpleBaseType": true
  of "ckConstructor, ckParameterList": true
  of "ckClass, ckConstructor": true
  of "ckClass, ckIndexer": true
  of "ckIndexer, ckPredefinedType": true
  of "ckIndexer, ckExplicitInterfaceSpecifier": true
  of "ckIndexer, ckBracketedParameterList": true
  of "ckIndexer, ckParameter": true
  of "ckIndexer, ckAccessorList": true
  of "ckAccessorList, ckAccessor": true
  of "ckClass, ckProperty": true
  of "ckProperty, ckPredefinedType": true
  of "ckProperty, ckAccessorList": true
  of "ckNamespace, ckUsingDirective": true
  of "ckMethod, ckExpressionStatement": true
  of "ckMethod, ckInvocationExpression": true
  of "ckExpressionStatement, ckInvocationExpression": true
  of "ckExpressionStatement, ckArgumentList": true
  of "ckExpressionStatement, ckArgument": true
  of "ckConstructor, ckExpressionStatement": true
  of "ckConstructor, ckAssignmentExpression": true
  of "ckConstructor, ckConstructorInitializer": true
  of "ckConstructor, ckArgumentList": true # likely for initializer
  of "ckLocalDeclarationStatement, ckVariable": true
  of "ckLocalDeclarationStatement, ckGenericName": true
  of "ckLocalDeclarationStatement, ckTypeArgumentList": true
  of "ckLocalDeclarationStatement, ckVariableDeclarator": true
  of "ckVariableDeclarator, ckEqualsValueClause": true
  of "ckVariableDeclarator, ckObjectCreationExpression": true
  of "ckLocalDeclarationStatement, ckArgumentList": true
  of "ckMethod, ckAssignmentExpression": true
  of "ckAssignmentExpression, ckObjectCreationExpression": true
  of "ckReturnStatement, ckObjectCreationExpression": true
  of "ckReturnStatement, ckArgumentList": true
  of "ckLocalDeclarationStatement, ckLiteralExpression": true
  of "ckAssignmentExpression, ckGenericName": true
  of "ckAssignmentExpression, ckTypeArgumentList": true
  of "ckAssignmentExpression, ckArgumentList": true
  of "ckObjectCreationExpression, ckInitializerExpression": true
  of "ckInitializerExpression, ckLiteralExpression": true
  of "ckLiteralExpression, ckPrefixUnaryExpression": true
  of "ckInitializerExpression, ckPrefixUnaryExpression": true
  of "ckVariableDeclarator, ckBinaryExpression": true
  of "ckVariable, ckGenericName": true
  of "ckObjectCreationExpression, ckGenericName": true
  of "ckGenericName, ckTypeArgumentList": true
  of "ckUsingDirective, ckNameEquals": true
  of "ckNameEquals, ckGenericName": true
  of "ckParameter, ckGenericName": true
  of "ckField, ckVariable": true
  of "ckReturnStatement, ckMemberAccessExpression": true
  of "ckField, ckVariableDeclarator": true
  of "ckMethod, ckVariableDeclarator": true
  of "ckVariableDeclarator, ckMemberAccessExpression": true
  of "ckInvocationExpression, ckMemberAccessExpression": true
  of "ckVariable, ckPredefinedType": true
  of "ckVariable, ckVariableDeclarator": true
  of "ckEqualsValueClause, ckLiteralExpression": true
  of "ckInvocationExpression, ckArgumentList": true
  of "ckConditionalExpression, ckPrefixUnaryExpression": true
  of "ckSimpleLambdaExpression, ckConditionalExpression": true
  of "ckInitializerExpression, ckConditionalExpression": true
  of "ckConditionalExpression, ckThisExpression": true
  of "ckArrayRankSpecifier, ckMemberAccessExpression": true
  of "ckInitializerExpression, ckTypeOfExpression": true
  of "ckEqualsValueClause, ckParenthesizedExpression": true
  of "ckCastExpression, ckConditionalAccessExpression": true
  of "ckNamespace, ckStruct": true
  of "ckSimpleLambdaExpression, ckQueryExpression": true
  of "ckArgument, ckDeclarationExpression": true
  of "ckTypeArgumentList, ckTupleType": true
  of "ckEqualsValueClause, ckAnonymousObjectCreationExpression": true
  of "ckBinaryExpression, ckIsPatternExpression": true
  of "ckArgument, ckAwaitExpression": true
  of "ckIfStatement, ckIsPatternExpression": true
  of "ckClass, ckStruct": true
  of "ckMethod, ckLockStatement": true
  of "ckAssignmentExpression, ckImplicitArrayCreationExpression": true
  of "ckForStatement, ckEmptyStatement": true
  of "ckAssignmentExpression, ckImplicitElementAccess": true
  of "ckConditionalExpression, ckAwaitExpression": true
  of "ckEqualsValueClause, ckQueryExpression": true
  of "ckVariable, ckRefType": true
  of "ckMethod, ckTupleType": true
  of "ckVariable, ckPointerType": true
  of "ckExpressionStatement, ckConditionalAccessExpression": true
  of "ckIfStatement, ckYieldStatement": true
  of "ckParenthesizedExpression, ckQueryExpression": true
  of "ckIfStatement, ckContinueStatement": true
  of "ckUsingDirective, ckAliasQualifiedName": true
  of "ckAssignmentExpression, ckDeclarationExpression": true
  of "ckBinaryExpression, ckThrowExpression": true
  of "ckCastExpression, ckElementAccessExpression": true
  of "ckCastExpression, ckObjectCreationExpression": true
  of "ckConstructor, ckReturnStatement": true
  of "ckCastExpression, ckCastExpression": true
  of "ckConditionalExpression, ckObjectCreationExpression": true
  of "ckArgumentList, ckArgument": true
  of "ckPostfixUnaryExpression, ckElementAccessExpression": true
  of "ckIfStatement, ckElementAccessExpression": true
  of "ckElementAccessExpression, ckParenthesizedExpression": true
  of "ckPostfixUnaryExpression, ckInvocationExpression": true
  of "ckParenthesizedLambdaExpression, ckTypeOfExpression": true
  of "ckInitializerExpression, ckSimpleLambdaExpression": true
  of "ckArgument, ckLiteralExpression": true
  of "ckTypeArgumentList, ckPredefinedType": true
  of "ckEqualsValueClause, ckObjectCreationExpression": true
  of "ckObjectCreationExpression, ckArgumentList": true
  of "ckPrefixUnaryExpression, ckLiteralExpression": true
  of "ckParameter, ckPredefinedType": true
  of "ckBracketedParameterList, ckParameter": true
  of "ckEqualsValueClause, ckMemberAccessExpression": true
  of "ckEqualsValueClause, ckBinaryExpression": true
  of "ckBaseList, ckSimpleBaseType": true
  of "ckArgument, ckAssignmentExpression": true
  of "ckArgument, ckBinaryExpression": true
  of "ckArgument, ckInvocationExpression": true
  of "ckArgument, ckMemberAccessExpression": true
  of "ckArgument, ckObjectCreationExpression": true
  of "ckArgument, ckPrefixUnaryExpression": true
  of "ckClass, ckClass": true
  of "ckClass, ckEnum": true
  of "ckConstructor, ckLocalDeclarationStatement": true
  of "ckConstructorInitializer, ckArgumentList": true
  of "ckEqualsValueClause, ckInvocationExpression": true
  of "ckExpressionStatement, ckAssignmentExpression": true
  of "ckInitializerExpression, ckAssignmentExpression": true
  of "ckInitializerExpression, ckInitializerExpression": true
  of "ckInitializerExpression, ckMemberAccessExpression": true
  of "ckInitializerExpression, ckObjectCreationExpression": true
  of "ckMemberAccessExpression, ckGenericName": true
  of "ckMemberAccessExpression, ckInvocationExpression": true
  of "ckMemberAccessExpression, ckMemberAccessExpression": true
  of "ckMemberAccessExpression, ckObjectCreationExpression": true
  of "ckMethod, ckGenericName": true
  of "ckObjectCreationExpression, ckPredefinedType": true
  of "ckParameter, ckEqualsValueClause": true
  of "ckReturnStatement, ckInvocationExpression": true
  of "ckTypeArgumentList, ckGenericName": true
  of "ckUsingDirective, ckGenericName": true
  of "ckLockStatement, ckThisExpression": true
  of "ckNullableType, ckGenericName": true
  of "ckConditionalAccessExpression, ckInvocationExpression": true
  of "ckYieldStatement, ckArrayCreationExpression": true
  of "ckIsPatternExpression, ckConditionalAccessExpression": true
  of "ckImplicitArrayCreationExpression, ckInitializerExpression": true
  of "ckNullableType, ckArrayType": true
  of "ckAwaitExpression, ckInvocationExpression": true
  of "ckPointerType, ckPredefinedType": true
  of "ckForEachStatement, ckInvocationExpression": true
  of "ckInterface, ckMethod": true
  of "ckElseClause, ckIfStatement": true
  of "ckNullableType, ckPredefinedType": true
  of "ckForEachStatement, ckExpressionStatement": true
  of "ckForEachStatement, ckMemberAccessExpression": true
  of "ckStruct, ckBaseList": true
  of "ckYieldStatement, ckObjectCreationExpression": true
  of "ckYieldStatement, ckLiteralExpression": true
  of "ckStruct, ckTypeParameterList": true
  of "ckStruct, ckEnum": true
  of "ckElseClause, ckExpressionStatement": true
  of "ckStruct, ckConstructor": true
  of "ckElseClause, ckThrowStatement": true
  of "ckInterface, ckProperty": true
  of "ckStruct, ckField": true
  of "ckAwaitExpression, ckParenthesizedExpression": true
  of "ckInterface, ckTypeParameterList": true
  of "ckSwitchStatement, ckMemberAccessExpression": true
  of "ckInterface, ckBaseList": true
  of "ckForEachStatement, ckPredefinedType": true
  of "ckReturnStatement, ckAwaitExpression": true
  of "ckElseClause, ckReturnStatement": true
  of "ckStruct, ckProperty": true
  of "ckBinaryExpression, ckBinaryExpression": true
  of "ckBinaryExpression, ckInvocationExpression": true
  of "ckReturnStatement, ckBinaryExpression": true
  of "ckSimpleBaseType, ckGenericName": true
  of "ckBinaryExpression, ckMemberAccessExpression": true
  of "ckBinaryExpression, ckLiteralExpression": true
  of "ckAssignmentExpression, ckMemberAccessExpression": true
  of "ckClass, ckTypeParameterList": true
  of "ckTypeParameterList, ckTypeParameter": true
  of "ckClass, ckTypeParameterConstraintClause": true
  of "ckTypeParameterConstraintClause, ckTypeConstraint": true
  of "ckTypeConstraint, ckGenericName": true
  of "ckInvocationExpression, ckGenericName": true
  of "ckMethod, ckIfStatement": true
  of "ckIfStatement, ckBinaryExpression": true
  of "ckBinaryExpression, ckTypeOfExpression": true
  of "ckAssignmentExpression, ckCastExpression": true
  of "ckCastExpression, ckThisExpression": true
  of "ckParameter, ckArrayType": true
  of "ckArrayType, ckPredefinedType": true
  of "ckArrayType, ckArrayRankSpecifier": true
  of "ckArrayRankSpecifier, ckOmittedArraySizeExpression": true
  of "ckMethod, ckArrowExpressionClause": true
  of "ckArrowExpressionClause, ckInvocationExpression": true
  of "ckArgument, ckSimpleLambdaExpression": true
  of "ckSimpleLambdaExpression, ckParameter": true
  of "ckIfStatement, ckInvocationExpression": true
  of "ckMethod, ckForStatement": true
  of "ckForStatement, ckVariable": true
  of "ckVariable, ckArrayType": true
  of "ckEqualsValueClause, ckInitializerExpression": true
  of "ckForStatement, ckBinaryExpression": true
  of "ckMethod, ckDoStatement": true
  of "ckForStatement, ckPostfixUnaryExpression": true
  of "ckMemberAccessExpression, ckElementAccessExpression": true
  of "ckElementAccessExpression, ckBracketedArgumentList": true
  of "ckBracketedArgumentList, ckArgument": true
  of "ckIfStatement, ckBreakStatement": true
  of "ckNameEquals, ckPrefixUnaryExpression": true
  of "ckMemberAccessExpression, ckThisExpression": true
  of "ckAssignmentExpression, ckLiteralExpression": true
  of "ckMethod, ckWhileStatement": true
  of "ckWhileStatement, ckBinaryExpression": true
  of "ckExpressionStatement, ckPostfixUnaryExpression": true
  of "ckIfStatement, ckPrefixUnaryExpression": true
  of "ckPrefixUnaryExpression, ckInvocationExpression": true
  of "ckBinaryExpression, ckParenthesizedExpression": true
  of "ckParenthesizedExpression, ckBinaryExpression": true
  of "ckArgument, ckInterpolatedStringExpression": true
  of "ckInterpolatedStringExpression, ckInterpolatedStringText": true
  of "ckMethod, ckArrayType": true
  of "ckIfStatement, ckThrowStatement": true
  of "ckThrowStatement, ckObjectCreationExpression": true
  of "ckArgument, ckConditionalExpression": true
  of "ckConditionalExpression, ckParenthesizedExpression": true
  of "ckConditionalExpression, ckLiteralExpression": true
  of "ckConditionalExpression, ckMemberAccessExpression": true
  of "ckMemberAccessExpression, ckPredefinedType": true
  of "ckEqualsValueClause, ckArrayCreationExpression": true
  of "ckArrayCreationExpression, ckArrayType": true
  of "ckIfStatement, ckExpressionStatement": true
  of "ckAssignmentExpression, ckArrayCreationExpression": true
  of "ckArrayCreationExpression, ckInitializerExpression": true
  of "ckInitializerExpression, ckArrayCreationExpression": true
  of "ckMethod, ckUsingStatement": true
  of "ckUsingStatement, ckVariable": true
  of "ckUsingStatement, ckUsingStatement": true
  of "ckUsingStatement, ckExpressionStatement": true
  of "ckAssignmentExpression, ckInvocationExpression": true
  of "ckElementAccessExpression, ckElementAccessExpression": true
  of "ckArgument, ckParenthesizedLambdaExpression": true
  of "ckParenthesizedLambdaExpression, ckParameterList": true
  of "ckMethod, ckTryStatement": true
  of "ckTryStatement, ckCatchClause": true
  of "ckCatchClause, ckCatch": true
  of "ckAssignmentExpression, ckAssignmentExpression": true
  of "ckAccessor, ckReturnStatement": true
  of "ckReturnStatement, ckElementAccessExpression": true
  of "ckProperty, ckExplicitInterfaceSpecifier": true
  of "ckArrowExpressionClause, ckBinaryExpression": true
  of "ckPrefixUnaryExpression, ckObjectCreationExpression": true
  of "ckMethod, ckThrowStatement": true
  of "ckTypeArgumentList, ckArrayType": true
  of "ckForStatement, ckPrefixUnaryExpression": true
  of "ckParenthesizedLambdaExpression, ckMemberAccessExpression": true
  of "ckSimpleLambdaExpression, ckBinaryExpression": true
  of "ckProperty, ckGenericName": true
  of "ckMemberAccessExpression, ckTypeOfExpression": true
  of "ckSimpleLambdaExpression, ckInvocationExpression": true
  of "ckAssignmentExpression, ckInitializerExpression": true
  of "ckSimpleLambdaExpression, ckAssignmentExpression": true
  of "ckArgument, ckTypeOfExpression": true
  of "ckWhileStatement, ckExpressionStatement": true
  of "ckAccessor, ckArrowExpressionClause": true
  of "ckParenthesizedLambdaExpression, ckCastExpression": true
  of "ckExplicitInterfaceSpecifier, ckGenericName": true
  of "ckReturnStatement, ckPostfixUnaryExpression": true
  of "ckArgument, ckPostfixUnaryExpression": true
  of "ckNamespace, ckExternAliasDirective": true
  of "ckParenthesizedExpression, ckObjectCreationExpression": true
  of "ckSimpleLambdaExpression, ckSimpleLambdaExpression": true
  of "ckParenthesizedExpression, ckArrayCreationExpression": true
  of "ckSimpleBaseType, ckPredefinedType": true
  of "ckSimpleLambdaExpression, ckParenthesizedExpression": true
  of "ckEqualsValueClause, ckAssignmentExpression": true
  of "ckIfStatement, ckParenthesizedExpression": true
  of "ckElementAccessExpression, ckObjectCreationExpression": true
  of "ckInterpolation, ckPrefixUnaryExpression": true
  of "ckBinaryExpression, ckThisExpression": true
  of "ckInvocationExpression, ckLiteralExpression": true
  of "ckSimpleLambdaExpression, ckLiteralExpression": true
  of "ckForStatement, ckIfStatement": true
  of "ckConditionalExpression, ckTypeOfExpression": true
  of "ckAssignmentExpression, ckParenthesizedExpression": true
  of "ckInterpolation, ckLiteralExpression": true
  of "ckIfStatement, ckConditionalExpression": true
  of "ckInterpolation, ckBinaryExpression": true
  of "ckParenthesizedExpression, ckLiteralExpression": true
  of "ckBinaryExpression, ckPostfixUnaryExpression": true
  of "ckTypeOfExpression, ckArrayType": true
  of "ckConditionalExpression, ckInterpolatedStringExpression": true
  of "ckMethod, ckCastExpression": true
  of "ckCastExpression, ckPrefixUnaryExpression": true
  of "ckParenthesizedLambdaExpression, ckParenthesizedLambdaExpression": true
  of "ckPredefinedType, ckGenericName": true
  of "ckMemberAccessExpression, ckArrayCreationExpression": true
  of "ckUsingStatement, ckIfStatement": true
  of "ckElementAccessExpression, ckThisExpression": true
  of "ckParenthesizedLambdaExpression, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckParenthesizedLambdaExpression": true
  of "ckIfStatement, ckIfStatement": true
  of "ckConstructor, ckArrowExpressionClause": true
  of "ckInitializerExpression, ckBinaryExpression": true
  of "ckBinaryExpression, ckArrayType": true
  of "ckThrowStatement, ckLiteralExpression": true
  of "ckUsingStatement, ckAssignmentExpression": true
  of "ckUsingStatement, ckCastExpression": true
  of "ckPrefixUnaryExpression, ckCastExpression": true
  of "ckIfStatement, ckLiteralExpression": true
  of "ckSimpleLambdaExpression, ckPrefixUnaryExpression": true
  of "ckInvocationExpression, ckInvocationExpression": true
  of "ckArgument, ckThisExpression": true
  of "ckEqualsValueClause, ckConditionalExpression": true
  of "ckMemberAccessExpression, ckParenthesizedExpression": true
  of "ckIfStatement, ckMemberAccessExpression": true
  of "ckProperty, ckEqualsValueClause": true
  of "ckProperty, ckLocalDeclarationStatement": true
  of "ckUsingStatement, ckMemberAccessExpression": true
  of "ckInterpolatedStringExpression, ckInterpolation": true
  of "ckInitializerExpression, ckParenthesizedLambdaExpression": true
  of "ckParenthesizedLambdaExpression, ckAssignmentExpression": true
  of "ckEqualsValueClause, ckParenthesizedLambdaExpression": true
  of "ckArgument, ckCastExpression": true
  of "ckArrayRankSpecifier, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckObjectCreationExpression": true
  of "ckAssignmentExpression, ckThisExpression": true
  of "ckBinaryExpression, ckElementAccessExpression": true
  of "ckMethod, ckTypeParameterList": true
  of "ckReturnStatement, ckCastExpression": true
  of "ckAssignmentExpression, ckBinaryExpression": true
  of "ckReturnStatement, ckConditionalExpression": true
  of "ckReturnStatement, ckAssignmentExpression": true
  of "ckParenthesizedLambdaExpression, ckPostfixUnaryExpression": true
  of "ckEqualsValueClause, ckCastExpression": true
  of "ckParenthesizedLambdaExpression, ckObjectCreationExpression": true
  of "ckForStatement, ckForStatement": true
  of "ckAssignmentExpression, ckSimpleLambdaExpression": true
  of "ckBinaryExpression, ckPrefixUnaryExpression": true
  of "ckIfStatement, ckReturnStatement": true
  of "ckParenthesizedLambdaExpression, ckConditionalExpression": true
  of "ckProperty, ckArrayType": true
  of "ckAssignmentExpression, ckParenthesizedLambdaExpression": true
  of "ckCastExpression, ckParenthesizedExpression": true
  of "ckProperty, ckArrowExpressionClause": true
  of "ckBinaryExpression, ckCastExpression": true
  of "ckSimpleLambdaExpression, ckMemberAccessExpression": true
  of "ckConditionalExpression, ckBinaryExpression": true
  of "ckArrowExpressionClause, ckArrayCreationExpression": true
  of "ckCastExpression, ckPredefinedType": true
  of "ckMemberAccessExpression, ckLiteralExpression": true
  of "ckUsingStatement, ckInvocationExpression": true
  of "ckArrowExpressionClause, ckCastExpression": true
  of "ckPrefixUnaryExpression, ckParenthesizedExpression": true
  of "ckExpressionStatement, ckLiteralExpression": true
  of "ckReturnStatement, ckInterpolatedStringExpression": true
  of "ckEnum, ckBaseList": true
  of "ckReturnStatement, ckArrayCreationExpression": true
  of "ckCastExpression, ckInvocationExpression": true
  of "ckMemberAccessExpression, ckInterpolatedStringExpression": true
  of "ckParenthesizedLambdaExpression, ckInvocationExpression": true
  of "ckPostfixUnaryExpression, ckMemberAccessExpression": true
  of "ckMethod, ckExplicitInterfaceSpecifier": true
  of "ckParenthesizedLambdaExpression, ckBinaryExpression": true
  of "ckArgument, ckElementAccessExpression": true
  of "ckArrayType, ckGenericName": true
  of "ckEqualsValueClause, ckPrefixUnaryExpression": true
  of "ckArrowExpressionClause, ckAssignmentExpression": true
  of "ckPrefixUnaryExpression, ckMemberAccessExpression": true
  of "ckArgument, ckArrayCreationExpression": true
  of "ckAssignmentExpression, ckElementAccessExpression": true
  of "ckForStatement, ckExpressionStatement": true
  of "ckArrowExpressionClause, ckMemberAccessExpression": true
  of "ckBinaryExpression, ckGenericName": true
  of "ckWhileStatement, ckInvocationExpression": true
  of "ckEqualsValueClause, ckElementAccessExpression": true
  of "ckAssignmentExpression, ckInterpolatedStringExpression": true
  of "ckParenthesizedExpression, ckPrefixUnaryExpression": true
  of "ckArrowExpressionClause, ckLiteralExpression": true
  of "ckCastExpression, ckMemberAccessExpression": true
  of "ckReturnStatement, ckTypeOfExpression": true
  of "ckInitializerExpression, ckInvocationExpression": true
  of "ckArrowExpressionClause, ckConditionalExpression": true
  of "ckNamespace, ckMethod": true
  of "ckAssignmentExpression, ckConditionalExpression": true
  of "ckEqualsValueClause, ckTypeOfExpression": true
  of "ckForStatement, ckAssignmentExpression": true
  of "ckArrayRankSpecifier, ckBinaryExpression": true
  of "ckAssignmentExpression, ckPrefixUnaryExpression": true
  of "ckSimpleLambdaExpression, ckObjectCreationExpression": true
  of "ckLiteralExpression, ckBinaryExpression": true
  of "ckReturnStatement, ckParenthesizedExpression": true
  of "ckBinaryExpression, ckPredefinedType": true
  of "ckExpressionStatement, ckObjectCreationExpression": true
  of "ckParenthesizedExpression, ckConditionalExpression": true
  of "ckArrowExpressionClause, ckInterpolatedStringExpression": true
  of "ckParenthesizedLambdaExpression, ckPrefixUnaryExpression": true
  of "ckParenthesizedExpression, ckParenthesizedLambdaExpression": true
  of "ckReturnStatement, ckSimpleLambdaExpression": true
  of "ckWhileStatement, ckLiteralExpression": true
  of "ckArrowExpressionClause, ckTypeOfExpression": true
  of "ckReturnStatement, ckPrefixUnaryExpression": true
  of "ckReturnStatement, ckThisExpression": true
  of "ckParenthesizedExpression, ckInvocationExpression": true
  of "ckReturnStatement, ckParenthesizedLambdaExpression": true
  of "ckMethod, ckTypeParameterConstraintClause": true
  of "ckInterpolation, ckMemberAccessExpression": true
  of "ckTypeOfExpression, ckGenericName": true
  of "ckElementAccessExpression, ckInvocationExpression": true
  of "ckCastExpression, ckArrayType": true
  of "ckCastExpression, ckGenericName": true
  of "ckCastExpression, ckLiteralExpression": true
  of "ckConditionalExpression, ckInvocationExpression": true
  of "ckInterpolation, ckInvocationExpression": true
  of "ckBinaryExpression, ckObjectCreationExpression": true
  of "ckElementAccessExpression, ckMemberAccessExpression": true
  of "ckWhileStatement, ckPrefixUnaryExpression": true
  of "ckExpressionStatement, ckPrefixUnaryExpression": true
  of "ckConditionalExpression, ckCastExpression": true
  of "ckEqualsValueClause, ckInterpolatedStringExpression": true
  of "ckParenthesizedExpression, ckAssignmentExpression": true
  of "ckEqualsValueClause, ckSimpleLambdaExpression": true
  of "ckArgument, ckParenthesizedExpression": true
  of "ckParenthesizedExpression, ckMemberAccessExpression": true
  of "ckInvocationExpression, ckElementAccessExpression": true
  of "ckParenthesizedExpression, ckCastExpression": true
  of "ckTypeOfExpression, ckPredefinedType": true
  of "ckInitializerExpression, ckCastExpression": true
  of "ckParenthesizedExpression, ckPostfixUnaryExpression": true
  of "ckElementAccessExpression, ckLiteralExpression": true
  of "ckIfStatement, ckCastExpression": true
  of "ckThrowStatement, ckCastExpression": true
  of "ckConditionalExpression, ckAssignmentExpression": true
  of "ckArrowExpressionClause, ckParenthesizedExpression": true
  of "ckMemberAccessExpression, ckPostfixUnaryExpression": true
  of "ckConditionalExpression, ckParenthesizedLambdaExpression": true
  of "ckConditionalExpression, ckElementAccessExpression": true
  of "ckThrowStatement, ckParenthesizedExpression": true
  of "ckIfStatement, ckTryStatement": true
  of "ckArrowExpressionClause, ckSimpleLambdaExpression": true
  of "ckBinaryExpression, ckArrayCreationExpression": true
  of "ckNamespace, ckConstructor": true
  of "ckArrowExpressionClause, ckElementAccessExpression": true
  of "ckExpressionStatement, ckCastExpression": true
  of "ckNamespace, ckProperty": true
  of "ckSimpleLambdaExpression, ckElementAccessExpression": true
  of "ckParenthesizedExpression, ckElementAccessExpression": true
  of "ckUsingStatement, ckObjectCreationExpression": true
  of "ckForStatement, ckLocalDeclarationStatement": true
  of "ckIndexer, ckArrowExpressionClause": true
  of "ckPrefixUnaryExpression, ckPrefixUnaryExpression": true
  of "ckUsingStatement, ckReturnStatement": true
  of "ckParenthesizedExpression, ckTypeOfExpression": true
  of "ckExpressionStatement, ckElementAccessExpression": true
  of "ckInterpolation, ckParenthesizedExpression": true
  of "ckPrefixUnaryExpression, ckElementAccessExpression": true
  of "ckInitializerExpression, ckElementAccessExpression": true
  of "ckConditionalExpression, ckArrayCreationExpression": true
  of "ckUsingStatement, ckWhileStatement": true
  of "ckInterpolation, ckAssignmentExpression": true
  of "ckCastExpression, ckPostfixUnaryExpression": true
  of "ckUsingStatement, ckConditionalExpression": true
  of "ckDoStatement, ckPrefixUnaryExpression": true
  of "ckParenthesizedLambdaExpression, ckInterpolatedStringExpression": true
  of "ckIfStatement, ckLocalDeclarationStatement": true
  of "ckExpressionStatement, ckMemberAccessExpression": true
  of "ckForStatement, ckMemberAccessExpression": true
  of "ckInterpolation, ckElementAccessExpression": true
  of "ckSimpleLambdaExpression, ckArrayCreationExpression": true
  of "ckUsingStatement, ckBinaryExpression": true
  of "ckCatch, ckGenericName": true
  of "ckPostfixUnaryExpression, ckParenthesizedExpression": true
  of "ckArrayRankSpecifier, ckConditionalExpression": true
  of "ckWhileStatement, ckIfStatement": true
  of "ckParenthesizedLambdaExpression, ckElementAccessExpression": true
  of "ckArrayRankSpecifier, ckInvocationExpression": true
  of "ckParenthesizedExpression, ckInterpolatedStringExpression": true
  of "ckAssignmentExpression, ckPostfixUnaryExpression": true
  of "ckCatch, ckPredefinedType": true
  of "ckInitializerExpression, ckParenthesizedExpression": true
  of "ckSimpleLambdaExpression, ckCastExpression": true
  of "ckParenthesizedExpression, ckParenthesizedExpression": true
  of "ckThrowStatement, ckInvocationExpression": true
  of "ckDoStatement, ckInvocationExpression": true
  of "ckSimpleLambdaExpression, ckInterpolatedStringExpression": true
  of "ckIndexer, ckGenericName": true
  of "ckConditionalExpression, ckConditionalExpression": true
  of "ckArgument, ckPredefinedType": true
  of "ckArgument, ckGenericName": true
  of "ckInitializerExpression, ckInterpolatedStringExpression": true
  of "ckExpressionStatement, ckThisExpression": true
  of "ckForStatement, ckParenthesizedExpression": true
  of "ckArrowExpressionClause, ckPrefixUnaryExpression": true
  of "ckAssignmentExpression, ckTypeOfExpression": true
  of "ckEqualsValueClause, ckPostfixUnaryExpression": true
  of "ckDoStatement, ckBinaryExpression": true
  of "ckIfStatement, ckAssignmentExpression": true
  of "ckInterpolation, ckPostfixUnaryExpression": true
  of "ckWhileStatement, ckForStatement": true
  of "ckForStatement, ckLiteralExpression": true
  of "ckArrayRankSpecifier, ckPrefixUnaryExpression": true
  of "ckVariableDeclarator, ckBracketedArgumentList": true
  of "ckInitializerExpression, ckPostfixUnaryExpression": true
  of "ckWhileStatement, ckElementAccessExpression": true
  of "ckArrayRankSpecifier, ckParenthesizedExpression": true
  of "ckWhileStatement, ckConditionalExpression": true
  of "ckSimpleLambdaExpression, ckPostfixUnaryExpression": true
  of "ckInvocationExpression, ckPredefinedType": true
  of "ckForStatement, ckInvocationExpression": true
  of "ckParenthesizedLambdaExpression, ckArrayCreationExpression": true
  of "ckWhileStatement, ckMemberAccessExpression": true
  of "ckInterpolation, ckTypeOfExpression": true
  of "ckInterpolation, ckCastExpression": true
  of "ckEqualsValueClause, ckThisExpression": true
  of "ckNamespace, ckField": true
  of "ckReturnStatement, ckImplicitArrayCreationExpression": true
  of "ckDelegate, ckParameterList": true
  of "ckArgument, ckAnonymousMethodExpression": true
  of "ckTypeArgumentList, ckNullableType": true
  of "ckBinaryExpression, ckConditionalAccessExpression": true
  of "ckArgument, ckNameColon": true
  of "ckBinaryExpression, ckAwaitExpression": true
  of "ckProperty, ckNullableType": true
  of "ckMethod, ckForEachStatement": true
  of "ckDelegate, ckGenericName": true
  of "ckArgument, ckImplicitArrayCreationExpression": true
  of "ckVariable, ckNullableType": true
  of "ckEqualsValueClause, ckImplicitArrayCreationExpression": true
  of "ckIfStatement, ckElseClause": true
  of "ckClass, ckDelegate": true
  of "ckAssignmentExpression, ckAwaitExpression": true
  of "ckParenthesizedLambdaExpression, ckAwaitExpression": true
  of "ckExpressionStatement, ckAwaitExpression": true
  of "ckMemberAccessExpression, ckBaseExpression": true
  of "ckEqualsValueClause, ckAnonymousMethodExpression": true
  of "ckInvocationExpression, ckCheckedExpression": true
  of "ckMethod, ckNullableType": true
  of "ckEqualsValueClause, ckCheckedExpression": true
  of "ckMethod, ckSwitchStatement": true
  of "ckArgument, ckBaseExpression": true
  of "ckArrowExpressionClause, ckConditionalAccessExpression": true
  of "ckTryStatement, ckFinallyClause": true
  of "ckAssignmentExpression, ckAnonymousMethodExpression": true
  of "ckDelegate, ckPredefinedType": true
  of "ckEqualsValueClause, ckConditionalAccessExpression": true
  of "ckElementAccessExpression, ckBaseExpression": true
  of "ckEqualsValueClause, ckAwaitExpression": true
  of "ckBinaryExpression, ckCheckedExpression": true
  of "ckParameter, ckNullableType": true
  of "ckNamespace, ckInterface": true
  of "ckClass, ckInterface": true
  of "ckMethod, ckYieldStatement": true
  of "ckArrowExpressionClause, ckImplicitArrayCreationExpression": true
  of "ckCastExpression, ckNullableType": true
  of "ckElementAccessExpression, ckPredefinedType": true
  of "ckArrowExpressionClause, ckPostfixUnaryExpression": true
  of "ckIfStatement, ckUsingStatement": true
  of "ckInterpolation, ckObjectCreationExpression": true
  of "ckInvocationExpression, ckParenthesizedLambdaExpression": true
  of "ckBinaryExpression, ckInterpolatedStringExpression": true
  of "ckPostfixUnaryExpression, ckLiteralExpression": true
  of "ckThrowStatement, ckMemberAccessExpression": true
  of "ckCastExpression, ckArrayCreationExpression": true
  of "ckDoStatement, ckLiteralExpression": true
  of "ckCatch, ckArrayType": true
  of "ckArrayRankSpecifier, ckCastExpression": true
  of "ckClass, ckGenericName": true
  of "ckIfStatement, ckForStatement": true
  of "ckInitializerExpression, ckThisExpression": true
  of "ckInvocationExpression, ckParenthesizedExpression": true
  of "ckExpressionStatement, ckBinaryExpression": true
  of "ckArrowExpressionClause, ckThisExpression": true
  of "ckSimpleBaseType, ckArrayType": true
  of "ckArrowExpressionClause, ckThrowExpression": true
  of "ckIfStatement, ckForEachStatement": true
  of "ckEqualsValueClause, ckDefaultExpression": true
  of "ckAssignmentExpression, ckDefaultExpression": true
  of "ckParameter, ckPointerType": true
  of "ckParenthesizedExpression, ckIsPatternExpression": true
  of "ckClass, ckIncompleteMember": true
  of "ckArgument, ckAnonymousObjectCreationExpression": true
  of "ckMethod, ckPointerType": true
  of "ckAssignmentExpression, ckConditionalAccessExpression": true
  of "ckInterpolation, ckInterpolationFormatClause": true
  of "ckReturnStatement, ckCheckedExpression": true
  of "ckSimpleLambdaExpression, ckAnonymousObjectCreationExpression": true
  of "ckSimpleBaseType, ckAliasQualifiedName": true
  of "ckDelegate, ckTypeParameterList": true
  of "ckArrayType, ckNullableType": true
  of "ckCastExpression, ckPointerType": true
  of "ckUsingStatement, ckEmptyStatement": true
  of "ckNamespace, ckIncompleteMember": true
  of "ckReturnStatement, ckConditionalAccessExpression": true
  of "ckArgument, ckDefaultExpression": true
  of "ckCastExpression, ckAwaitExpression": true
  of "ckWhileStatement, ckEmptyStatement": true
  of "ckIfStatement, ckEmptyStatement": true
  of "ckTypeArgumentList, ckOmittedTypeArgument": true
  of "ckArrayType, ckTupleType": true
  of "ckUsingStatement, ckAwaitExpression": true
  of "ckVariable, ckAliasQualifiedName": true
  of "ckArgument, ckCheckedExpression": true
  of "ckBinaryExpression, ckNullableType": true
  of "ckReturnStatement, ckSwitchExpression": true
  of "ckParenthesizedLambdaExpression, ckAnonymousObjectCreationExpression": true
  of "ckArgument, ckIsPatternExpression": true
  of "ckArrowExpressionClause, ckAwaitExpression": true
  of "ckUsingStatement, ckConditionalAccessExpression": true
  of "ckMethod, ckContinueStatement": true
  of "ckTypeOfExpression, ckPointerType": true
  of "ckAssignmentExpression, ckCheckedExpression": true
  of "ckArgument, ckImplicitObjectCreationExpression": true
  of "ckArgument, ckConditionalAccessExpression": true
  of "ckAssignmentExpression, ckImplicitObjectCreationExpression": true
  of "ckConditionalExpression, ckDefaultExpression": true
  of "ckSwitchStatement, ckInvocationExpression": true
  of "ckIsPatternExpression, ckConstantPattern": true
  of "ckCheckedExpression, ckCastExpression": true
  of "ckSwitchStatement, ckSwitchSection": true
  of "ckTupleType, ckTupleElement": true
  of "ckDeclarationExpression, ckSingleVariableDesignation": true
  of "ckQueryExpression, ckQueryBody": true
  of "ckIsPatternExpression, ckDeclarationPattern": true
  of "ckConditionalAccessExpression, ckMemberAccessExpression": true
  of "ckImplicitElementAccess, ckBracketedArgumentList": true
  of "ckStruct, ckIncompleteMember": true
  of "ckEqualsValueClause, ckRefExpression": true
  of "ckDeclarationExpression, ckPredefinedType": true
  of "ckYieldStatement, ckInvocationExpression": true
  of "ckConditionalAccessExpression, ckMemberBindingExpression": true
  of "ckParenthesizedLambdaExpression, ckThrowExpression": true
  of "ckStruct, ckMethod": true
  of "ckForEachStatement, ckThisExpression": true
  of "ckAnonymousObjectCreationExpression, ckAnonymousObjectMemberDeclarator": true
  of "ckSwitchStatement, ckCastExpression": true
  of "ckEqualsValueClause, ckImplicitObjectCreationExpression": true
  of "ckConditionalAccessExpression, ckParenthesizedExpression": true
  of "ckConditionalAccessExpression, ckConditionalAccessExpression": true
  of "ckReturnStatement, ckQueryExpression": true
  of "ckTypeOfExpression, ckNullableType": true
  of "ckIsPatternExpression, ckMemberAccessExpression": true
  of "ckForEachStatement, ckArrayCreationExpression": true
  of "ckDefaultExpression, ckPredefinedType": true
  of "ckAnonymousMethodExpression, ckParameterList": true
  of "ckCheckedExpression, ckBinaryExpression": true
  of "ckForStatement, ckYieldStatement": true
  of "ckForEachStatement, ckImplicitArrayCreationExpression": true
  of "ckForEachStatement, ckGenericName": true
  of "ckParenthesizedExpression, ckImplicitArrayCreationExpression": true
  of "ckForEachStatement, ckObjectCreationExpression": true
  of "ckDeclarationExpression, ckParenthesizedVariableDesignation": true
  of "ckMethod, ckRefType": true
  of "ckMethod, ckGotoStatement": true
  of "ckAwaitExpression, ckMemberAccessExpression": true
  of "ckConditionalExpression, ckConditionalAccessExpression": true
  of "ckParenthesizedLambdaExpression, ckConditionalAccessExpression": true
  of "ckArrowExpressionClause, ckQueryExpression": true
  of "ckSwitchStatement, ckConditionalAccessExpression": true
  of "ckDeclarationExpression, ckNullableType": true
  of "ckIndexer, ckNullableType": true
  of "ckStruct, ckDelegate": true
  of "ckParenthesizedLambdaExpression, ckRefExpression": true
  of "ckForEachStatement, ckYieldStatement": true
  of "ckReturnStatement, ckDefaultExpression": true
  of "ckWhileStatement, ckIsPatternExpression": true
  of "ckLockStatement, ckMemberAccessExpression": true
  of "ckArgument, ckQueryExpression": true
  of "ckConditionalExpression, ckImplicitArrayCreationExpression": true
  of "ckYieldStatement, ckMemberAccessExpression": true
  of "ckSimpleLambdaExpression, ckThrowExpression": true
  of "ckPointerType, ckPointerType": true
  of "ckIsPatternExpression, ckUnaryPattern": true
  of "ckEqualsValueClause, ckStackAllocArrayCreationExpression": true
  of "ckSwitchStatement, ckPrefixUnaryExpression": true
  of "ckParenthesizedExpression, ckCheckedExpression": true
  of "ckForEachStatement, ckPostfixUnaryExpression": true
  of "ckMemberAccessExpression, ckImplicitArrayCreationExpression": true
  of "ckSwitchStatement, ckBinaryExpression": true
  of "ckForEachStatement, ckArrayType": true
  of "ckEqualsValueClause, ckIsPatternExpression": true
  of "ckEqualsValueClause, ckTupleExpression": true
  of "ckEqualsValueClause, ckSwitchExpression": true
  of "ckForEachStatement, ckIfStatement": true
  of "ckIfStatement, ckGotoStatement": true
  of "ckInterface, ckIndexer": true
  of "ckYieldStatement, ckInterpolatedStringExpression": true
  of "ckEqualsValueClause, ckMakeRefExpression": true
  of "ckInitializerExpression, ckAwaitExpression": true
  of "ckIndexer, ckRefType": true
  of "ckCatchClause, ckCatchFilterClause": true
  of "ckConditionalExpression, ckIsPatternExpression": true
  of "ckArgument, ckRangeExpression": true
  of "ckArgument, ckAliasQualifiedName": true
  of "ckForEachStatement, ckCastExpression": true
  of "ckYieldStatement, ckBinaryExpression": true
  of "ckArrowExpressionClause, ckSwitchExpression": true
  of "ckDeclarationExpression, ckGenericName": true
  of "ckSwitchStatement, ckElementAccessExpression": true
  of "ckSwitchStatement, ckLiteralExpression": true
  of "ckSimpleLambdaExpression, ckImplicitArrayCreationExpression": true
  of "ckInitializerExpression, ckImplicitArrayCreationExpression": true
  of "ckLockStatement, ckTypeOfExpression": true
  of "ckMemberAccessExpression, ckAnonymousObjectCreationExpression": true
  of "ckLockStatement, ckLockStatement": true
  of "ckArgument, ckTupleExpression": true
  of "ckInitializerExpression, ckDefaultExpression": true
  of "ckAssignmentExpression, ckTupleExpression": true
  of "ckForStatement, ckUsingStatement": true
  of "ckSwitchStatement, ckAwaitExpression": true
  of "ckBinaryExpression, ckDefaultExpression": true
  of "ckDeclarationExpression, ckDiscardDesignation": true
  else: raise newException(Exception, "cfits is missing:  of \"" & $parent.kind & ", " & $item.kind & "\": true")
