# lines_regex.nim

import nre

import tables
 # the names are from the CS side.
var dict* = {  
  "reInvocationExpressionSyntax" : re"...TODO" , #TODO
  "reUsingDirectiveSyntax" : re"...TODO" , #TODO
  "reNamespaceDeclarationSyntax" : re"...TODO" , #TODO
  "reQualifiedNameSyntax" : re"...TODO" , #TODO
  "reClassDeclarationSyntax" : re"...TODO" , #TODO
  "reMethodDeclarationSyntax" : re"...TODO" , #TODO
  "reBlockSyntax" : re"...TODO" , #TODO
  "reVariableDeclarationSyntax" : re"...TODO" , #TODO
  "reLiteralExpressionSyntax" : re"...TODO" , #TODO
  "reVariableDeclaratorSyntax" : re"...TODO" , #TODO
  "reArgumentListSyntax" : re"...TODO" , #TODO
  "rePredefinedTypeSyntax" : re"...TODO" , #TODO
  "reTypeParameterListSyntax" : re"...TODO" , #TODO
  "reArgumentSyntax" : re"...TODO" , #TODO
  "reExpressionStatementSyntax" : re"...TODO" , #TODO
  "reBinaryExpressionSyntax" : re"...TODO" , #TODO
  "reParameterSyntax" : re"...TODO" , #TODO
  "reAssignmentExpressionSyntax" : re"...TODO" , #TODO
  "reEqualsValueClauseSyntax" : re"...TODO" , #TODO
  "reParameterListSyntax" : re"...TODO" , #TODO
  "reLocalDeclarationStatementSyntax" : re"...TODO" , #TODO
  "reObjectCreationExpressionSyntax" : re"...TODO" , #TODO
  "reReturnStatementSyntax" : re"...TODO" , #TODO
  "reIfStatementSyntax" : re"...TODO" , #TODO
  "reAccessorDeclarationSyntax" : re"...TODO" , #TODO
  "reAccessorListSyntax" : re"...TODO" , #TODO
  "reAliasQualifiedNameSyntax" : re"...TODO" , #TODO
  "reAnonymousMethodExpressionSyntax" : re"...TODO" , #TODO
  "reAnonymousObjectCreationExpressionSyntax" : re"...TODO" , #TODO
  "reAnonymousObjectMemberDeclaratorSyntax" : re"...TODO" , #TODO
  "reArrayCreationExpressionSyntax" : re"...TODO" , #TODO
  "reArrayRankSpecifierSyntax" : re"...TODO" , #TODO
  "reArrayTypeSyntax" : re"...TODO" , #TODO
  "reArrowExpressionClauseSyntax" : re"...TODO" , #TODO
  "reAttributeSyntax" : re"...TODO" , #TODO
  "reAttributeArgumentSyntax" : re"...TODO" , #TODO
  "reAttributeArgumentListSyntax" : re"...TODO" , #TODO
  "reAttributeListSyntax" : re"...TODO" , #TODO
  "reAttributeTargetSpecifierSyntax" : re"...TODO" , #TODO
  "reAwaitExpressionSyntax" : re"...TODO" , #TODO
  "reBadDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reBaseExpressionSyntax" : re"...TODO" , #TODO
  "reBaseListSyntax" : re"...TODO" , #TODO
  "reBracketedArgumentListSyntax" : re"...TODO" , #TODO
  "reBracketedParameterListSyntax" : re"...TODO" , #TODO
  "reBreakStatementSyntax" : re"...TODO" , #TODO
  "reCasePatternSwitchLabelSyntax" : re"...TODO" , #TODO
  "reCaseSwitchLabelSyntax" : re"...TODO" , #TODO
  "reCastExpressionSyntax" : re"...TODO" , #TODO
  "reCatchClauseSyntax" : re"...TODO" , #TODO
  "reCatchDeclarationSyntax" : re"...TODO" , #TODO
  "reCatchFilterClauseSyntax" : re"...TODO" , #TODO
  "reCheckedExpressionSyntax" : re"...TODO" , #TODO
  "reCheckedStatementSyntax" : re"...TODO" , #TODO
  "reClassOrStructConstraintSyntax" : re"...TODO" , #TODO
  "reCompilationUnitSyntax" : re"...TODO" , #TODO
  "reConditionalAccessExpressionSyntax" : re"...TODO" , #TODO
  "reConditionalExpressionSyntax" : re"...TODO" , #TODO
  "reConstantPatternSyntax" : re"...TODO" , #TODO
  "reConstructorConstraintSyntax" : re"...TODO" , #TODO
  "reConstructorDeclarationSyntax" : re"...TODO" , #TODO
  "reConstructorInitializerSyntax" : re"...TODO" , #TODO
  "reContinueStatementSyntax" : re"...TODO" , #TODO
  "reConversionOperatorDeclarationSyntax" : re"...TODO" , #TODO
  "reConversionOperatorMemberCrefSyntax" : re"...TODO" , #TODO
  "reCrefBracketedParameterListSyntax" : re"...TODO" , #TODO
  "reCrefParameterSyntax" : re"...TODO" , #TODO
  "reCrefParameterListSyntax" : re"...TODO" , #TODO
  "reDeclarationExpressionSyntax" : re"...TODO" , #TODO
  "reDeclarationPatternSyntax" : re"...TODO" , #TODO
  "reDefaultExpressionSyntax" : re"...TODO" , #TODO
  "reDefaultSwitchLabelSyntax" : re"...TODO" , #TODO
  "reDefineDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reDelegateDeclarationSyntax" : re"...TODO" , #TODO
  "reDestructorDeclarationSyntax" : re"...TODO" , #TODO
  "reDiscardDesignationSyntax" : re"...TODO" , #TODO
  "reDocumentationCommentTriviaSyntax" : re"...TODO" , #TODO
  "reDoStatementSyntax" : re"...TODO" , #TODO
  "reElementAccessExpressionSyntax" : re"...TODO" , #TODO
  "reElementBindingExpressionSyntax" : re"...TODO" , #TODO
  "reElifDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reElseClauseSyntax" : re"...TODO" , #TODO
  "reElseDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reEmptyStatementSyntax" : re"...TODO" , #TODO
  "reEndIfDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reEndRegionDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reEnumDeclarationSyntax" : re"...TODO" , #TODO
  "reEnumMemberDeclarationSyntax" : re"...TODO" , #TODO
  "reErrorDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reEventDeclarationSyntax" : re"...TODO" , #TODO
  "reEventFieldDeclarationSyntax" : re"...TODO" , #TODO
  "reExplicitInterfaceSpecifierSyntax" : re"...TODO" , #TODO
  "reExternAliasDirectiveSyntax" : re"...TODO" , #TODO
  "reFieldDeclarationSyntax" : re"...TODO" , #TODO
  "reFinallyClauseSyntax" : re"...TODO" , #TODO
  "reFixedStatementSyntax" : re"...TODO" , #TODO
  "reForEachStatementSyntax" : re"...TODO" , #TODO
  "reForEachVariableStatementSyntax" : re"...TODO" , #TODO
  "reForStatementSyntax" : re"...TODO" , #TODO
  "reFromClauseSyntax" : re"...TODO" , #TODO
  "reGenericNameSyntax" : re"...TODO" , #TODO
  "reGlobalStatementSyntax" : re"...TODO" , #TODO
  "reGotoStatementSyntax" : re"...TODO" , #TODO
  "reGroupClauseSyntax" : re"...TODO" , #TODO
  "reIdentifierNameSyntax" : re"...TODO" , #TODO
  "reIfDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reImplicitArrayCreationExpressionSyntax" : re"...TODO" , #TODO
  "reImplicitElementAccessSyntax" : re"...TODO" , #TODO
  "reImplicitStackAllocArrayCreationExpressionSyntax" : re"...TODO" , #TODO
  "reIncompleteMemberSyntax" : re"...TODO" , #TODO
  "reIndexerDeclarationSyntax" : re"...TODO" , #TODO
  "reIndexerMemberCrefSyntax" : re"...TODO" , #TODO
  "reInitializerExpressionSyntax" : re"...TODO" , #TODO
  "reInterfaceDeclarationSyntax" : re"...TODO" , #TODO
  "reInterpolatedStringExpressionSyntax" : re"...TODO" , #TODO
  "reInterpolatedStringTextSyntax" : re"...TODO" , #TODO
  "reInterpolationSyntax" : re"...TODO" , #TODO
  "reInterpolationAlignmentClauseSyntax" : re"...TODO" , #TODO
  "reInterpolationFormatClauseSyntax" : re"...TODO" , #TODO
  "reIsPatternExpressionSyntax" : re"...TODO" , #TODO
  "reJoinClauseSyntax" : re"...TODO" , #TODO
  "reJoinIntoClauseSyntax" : re"...TODO" , #TODO
  "reLabeledStatementSyntax" : re"...TODO" , #TODO
  "reLetClauseSyntax" : re"...TODO" , #TODO
  "reLineDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reLoadDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reLocalFunctionStatementSyntax" : re"...TODO" , #TODO
  "reLockStatementSyntax" : re"...TODO" , #TODO
  "reMakeRefExpressionSyntax" : re"...TODO" , #TODO
  "reMemberBindingExpressionSyntax" : re"...TODO" , #TODO
  "reNameColonSyntax" : re"...TODO" , #TODO
  "reNameEqualsSyntax" : re"...TODO" , #TODO
  "reNameMemberCrefSyntax" : re"...TODO" , #TODO
  "reNullableTypeSyntax" : re"...TODO" , #TODO
  "reOmittedArraySizeExpressionSyntax" : re"...TODO" , #TODO
  "reOmittedTypeArgumentSyntax" : re"...TODO" , #TODO
  "reOperatorDeclarationSyntax" : re"...TODO" , #TODO
  "reOperatorMemberCrefSyntax" : re"...TODO" , #TODO
  "reOrderByClauseSyntax" : re"...TODO" , #TODO
  "reOrderingSyntax" : re"...TODO" , #TODO
  "reParenthesizedExpressionSyntax" : re"...TODO" , #TODO
  "reParenthesizedLambdaExpressionSyntax" : re"...TODO" , #TODO
  "reParenthesizedVariableDesignationSyntax" : re"...TODO" , #TODO
  "rePointerTypeSyntax" : re"...TODO" , #TODO
  "rePostfixUnaryExpressionSyntax" : re"...TODO" , #TODO
  "rePragmaChecksumDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "rePragmaWarningDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "rePrefixUnaryExpressionSyntax" : re"...TODO" , #TODO
  "rePropertyDeclarationSyntax" : re"...TODO" , #TODO
  "reQualifiedCrefSyntax" : re"...TODO" , #TODO
  "reQueryBodySyntax" : re"...TODO" , #TODO
  "reQueryContinuationSyntax" : re"...TODO" , #TODO
  "reQueryExpressionSyntax" : re"...TODO" , #TODO
  "reReferenceDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reRefExpressionSyntax" : re"...TODO" , #TODO
  "reRefTypeSyntax" : re"...TODO" , #TODO
  "reRefTypeExpressionSyntax" : re"...TODO" , #TODO
  "reRefValueExpressionSyntax" : re"...TODO" , #TODO
  "reRegionDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reSelectClauseSyntax" : re"...TODO" , #TODO
  "reShebangDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reSimpleBaseTypeSyntax" : re"...TODO" , #TODO
  "reSimpleLambdaExpressionSyntax" : re"...TODO" , #TODO
  "reSingleVariableDesignationSyntax" : re"...TODO" , #TODO
  "reSizeOfExpressionSyntax" : re"...TODO" , #TODO
  "reSkippedTokensTriviaSyntax" : re"...TODO" , #TODO
  "reStackAllocArrayCreationExpressionSyntax" : re"...TODO" , #TODO
  "reStructDeclarationSyntax" : re"...TODO" , #TODO
  "reSwitchSectionSyntax" : re"...TODO" , #TODO
  "reSwitchStatementSyntax" : re"...TODO" , #TODO
  "reThisExpressionSyntax" : re"...TODO" , #TODO
  "reThrowExpressionSyntax" : re"...TODO" , #TODO
  "reThrowStatementSyntax" : re"...TODO" , #TODO
  "reTryStatementSyntax" : re"...TODO" , #TODO
  "reTupleElementSyntax" : re"...TODO" , #TODO
  "reTupleExpressionSyntax" : re"...TODO" , #TODO
  "reTupleTypeSyntax" : re"...TODO" , #TODO
  "reTypeArgumentListSyntax" : re"...TODO" , #TODO
  "reTypeConstraintSyntax" : re"...TODO" , #TODO
  "reTypeCrefSyntax" : re"...TODO" , #TODO
  "reTypeOfExpressionSyntax" : re"...TODO" , #TODO
  "reTypeParameterSyntax" : re"...TODO" , #TODO
  "reTypeParameterConstraintClauseSyntax" : re"...TODO" , #TODO
  "reUndefDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reUnsafeStatementSyntax" : re"...TODO" , #TODO
  "reUsingStatementSyntax" : re"...TODO" , #TODO
  "reWarningDirectiveTriviaSyntax" : re"...TODO" , #TODO
  "reWhenClauseSyntax" : re"...TODO" , #TODO
  "reWhereClauseSyntax" : re"...TODO" , #TODO
  "reWhileStatementSyntax" : re"...TODO" , #TODO
  "reYieldStatementSyntax" : re"...TODO" , #TODO
  "reMemberAccessExpressionSyntax" : re"...TODO" #TODO
  }.toTable()